// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

// Generating the credential contract: schema declaration -> a Cred type plus a registration function.
//
// Credentials were the last contract still living on "a struct with tags in package main, reflected at
// runtime" — operations and events had moved to declarations long before, and credentials simply had
// not followed. The cost was real: a tag cannot express enum candidates, a misspelled field name binds
// to nothing at runtime (with no generated type to catch it, unlike operations), and editing the
// credential contract did not trigger sokel-gen at all, so it needed a different mental model from the
// other two.

import (
	"encoding/json"
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// credentialMethods is the method set that makes a type a contract.CredentialSchema.
var credentialMethods = []string{"CredentialFields"}

// CredentialTypes finds the types in a package that declare a credential contract, usually at most one.
func (p *Package) CredentialTypes() []string { return p.typesWith(credentialMethods) }

// LoadCredential reads the credential declaration out of a schema package.
//
// Same path as operations and events: generate a temporary program that imports the package, flattens
// the declaration to JSON and prints it. A declaration is **executable code** (chained builder calls),
// so parsing it at the source level would mean reimplementing Go.
func LoadCredential(dir, importPath string, types []string) ([]Field, error) {
	if len(types) == 0 {
		return nil, nil
	}
	if len(types) > 1 {
		// A plugin has one credential contract. Several means the declaration went wrong, and saying so
		// beats generating whichever one happened to come first.
		return nil, fmt.Errorf("there can be only one credential declaration; found %d: %s", len(types), strings.Join(types, ", "))
	}
	out, err := runLoader(dir, renderCredentialLoader(importPath, types[0]))
	if err != nil {
		return nil, err
	}
	var fields []Field
	if err := json.Unmarshal(out, &fields); err != nil {
		return nil, fmt.Errorf("parsing the credential declaration failed: %w\n%s", err, truncate(string(out), 300))
	}
	return fields, checkCredTypes(fields)
}

// credFieldTypes are the field types the credential form understands.
//
// They are **not the same vocabulary** as operation fields: those are string/number/boolean and so on,
// while these are form controls. Getting it wrong raises nothing and silently degrades to a plain text
// input — declare a dropdown, get a text box, and the author will most likely blame the frontend.
var credFieldTypes = map[string]string{
	"text": "", "secret": "", "select": "", "url": "", "secret-file": "", "header-list": "",
}

func checkCredTypes(fields []Field) error {
	for _, f := range fields {
		if _, ok := credFieldTypes[f.Type]; !ok {
			return fmt.Errorf("the credential form does not recognise type %[2]q on field %[1]q; use field.Text / field.Secret / field.Select — credential types are form controls, not the string/number vocabulary",
				f.Name, f.Type)
		}
	}
	return nil
}

func renderCredentialLoader(importPath, typ string) string {
	var b strings.Builder
	b.WriteString("// Generated by sokel-gen as a temporary program; deleted right after it runs.\npackage main\n\nimport (\n\t\"encoding/json\"\n\t\"os\"\n\n")
	b.WriteString("\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n")
	if importPath != "" {
		b.WriteString("\tsch " + strconv.Quote(importPath) + "\n")
	}
	b.WriteString(")\n\nfunc main() {\n")
	ref := "&sch." + typ + "{}"
	if importPath == "" {
		ref = "&" + typ + "{}"
	}
	b.WriteString("\tfields := contract.CredentialOf(" + ref + ")\n")
	b.WriteString("\tif err := json.NewEncoder(os.Stdout).Encode(fields); err != nil {\n\t\tos.Exit(1)\n\t}\n}\n")
	return b.String()
}

// RenderCredential generates zz_credential.go: the Cred type plus RegisterCredential.
//
// Both are needed:
//   - the Cred type is what sokel.CredentialAs[Cred](ctx) binds into, with field names fixed by the
//     declaration so a typo is a compile error;
//   - the registration function reports **the declared fields as they are**, rather than reflecting
//     over Cred again. Reflection cannot produce enum candidates, so going back through it would throw
//     away the expressiveness just gained.
//
// It takes a plugin.CredentialHost rather than a *sokel.Plugin, so the generated file does not import
// the SDK. An in-process kernel can then use the same generator without forming an import cycle.
func RenderCredential(pkg string, sch SchemaRef, fields []Field) (string, error) {
	if len(fields) == 0 {
		return "", fmt.Errorf("the credential declaration has no fields")
	}
	need := &imports{}
	body := renderCredStruct(fields, qual(sch.Name), need)

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// The credential contract is generated from the schema declaration.\n// Change it there, then regenerate.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n\t\"github.com/sokel-dev/sokel-plugin-sdk/plugin\"\n")
	if sch.Import != "" && need.schema {
		b.WriteString("\t" + strconv.Quote(sch.Import) + "\n")
	}
	b.WriteString(")\n\n")
	b.WriteString(body)

	b.WriteString("// credentialContract is the credential contract reported to the platform, exactly as declared.\n")
	b.WriteString("func credentialContract() []contract.Field {\n\treturn " + renderFields(fields, 1, "contract") + "\n}\n\n")
	b.WriteString("// RegisterCredential reports this plugin's credential contract. It replaces the older\n")
	b.WriteString("// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than\n")
	b.WriteString("// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.\n")
	b.WriteString("func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("the generated credential code will not format (most likely a rendering bug): %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// renderCredStruct renders the Cred type. The sokel tags are there so sokel.CredentialAs[Cred] can
// bind by contract name; **the contract itself is not reflected from them** (see RenderCredential),
// and the tags are only binding keys.
func renderCredStruct(fields []Field, schemaPkg string, need *imports) string {
	var b strings.Builder
	b.WriteString("// Cred is this plugin's credential contract, generated from the schema declaration.\n")
	b.WriteString("// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()[\"raw key\"]: a misspelled\n// raw key compiles fine and silently binds nothing.\n")
	b.WriteString("type Cred struct {\n")
	for _, f := range fields {
		tag := f.Name
		if !f.Required {
			tag += ",optional"
		}
		line := fmt.Sprintf("\t%s %s `sokel:%s", exportName(f.Name), goType(f, schemaPkg, "Cred", need, 1), strconv.Quote(tag))
		if f.Label != "" {
			line += " label:" + strconv.Quote(f.Label)
		}
		if f.Type == "secret" {
			line += ` secret:"true"`
		}
		if d, ok := f.Default.(string); ok && d != "" {
			line += " default:" + strconv.Quote(d) // the fallback when reading; the platform's own default rides the contract field
		}
		b.WriteString(line + "`\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

// —— the auth flow: how a credential is obtained ——

// authMethods is the method set that makes a type a contract.AuthSchema; it hangs off the credential
// declaration.
var authMethods = []string{"AuthMeta"}

// AuthTypes finds the types that declare an authentication method.
func (p *Package) AuthTypes() []string { return p.typesWith(authMethods) }

// AuthMeta is the content of an authentication declaration, shaped like contract.AuthMeta for the JSON
// round trip.
type AuthMeta struct {
	Kind     string   `json:"Kind"`
	Steps    []string `json:"Steps"`
	Provider string   `json:"Provider"`
	Scopes   []string `json:"Scopes"`
}

// LoadAuth reads the authentication declaration out of a schema package.
func LoadAuth(dir, importPath string, types []string) (*AuthMeta, error) {
	if len(types) == 0 {
		return nil, nil
	}
	if len(types) > 1 {
		return nil, fmt.Errorf("there can be only one authentication declaration; found %d: %s", len(types), strings.Join(types, ", "))
	}
	out, err := runLoader(dir, renderAuthLoader(importPath, types[0]))
	if err != nil {
		return nil, err
	}
	var meta AuthMeta
	if err := json.Unmarshal(out, &meta); err != nil {
		return nil, fmt.Errorf("parsing the authentication declaration failed: %w\n%s", err, truncate(string(out), 300))
	}
	return &meta, checkAuthMeta(meta)
}

var authKinds = map[string]string{"qr": "AuthQR", "input": "AuthInput", "oauth": "AuthOAuth"}

func kindConst(kind string) string { return authKinds[kind] }

var authSteps = map[string]bool{"start": true, "poll": true, "submit": true}

// scopelessProviders are the providers for which scopes do not exist.
//
// One of them grants permissions by having the user tick pages on the consent screen, with no scope
// parameter in the request at all. Requiring a non-empty value the way another provider needs would
// force such a plugin to fill in something the upstream will reject. The platform keeps a matching
// list, and a new provider goes into both.
var scopelessProviders = map[string]bool{"notion": true}

func checkAuthMeta(m AuthMeta) error {
	if authKinds[m.Kind] == "" {
		return fmt.Errorf("unknown authentication kind %q (qr / input / oauth)", m.Kind)
	}
	for _, s := range m.Steps {
		if !authSteps[s] {
			return fmt.Errorf("unknown authentication step %q (start / poll / submit)", s)
		}
	}
	switch m.Kind {
	case "oauth":
		// The platform answers start and poll for oauth, so declaring steps promises an implementation
		// that will never be called.
		if len(m.Steps) > 0 {
			return fmt.Errorf("kind=oauth must not declare Steps — the platform answers start/poll, since the client secret lives there and a plugin cannot build the consent URL")
		}
		if m.Provider == "" {
			return fmt.Errorf("kind=oauth requires a Provider; the platform picks the exchange flow from it")
		}
		// Scopes are declared by the plugin rather than hard-coded in the platform. Leaving them empty
		// for a provider that needs them asks for a consent page that will certainly be refused — but
		// **not every provider has scopes**, see scopelessProviders.
		if len(m.Scopes) == 0 && !scopelessProviders[m.Provider] {
			return fmt.Errorf("kind=oauth requires Scopes; they are declared by the plugin, not hard-coded in the platform")
		}
	default:
		// One step short leaves the panel stuck on it. Catching that here spares the author from scanning
		// a code only to find there is no poll.
		var has = map[string]bool{}
		for _, s := range m.Steps {
			has[s] = true
		}
		if !has["start"] || !has["poll"] {
			return fmt.Errorf("kind=%s must declare both the start and poll steps", m.Kind)
		}
	}
	return nil
}

func renderAuthLoader(importPath, typ string) string {
	var b strings.Builder
	b.WriteString("// Generated by sokel-gen as a temporary program; deleted right after it runs.\npackage main\n\nimport (\n\t\"encoding/json\"\n\t\"os\"\n\n")
	b.WriteString("\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n")
	if importPath != "" {
		b.WriteString("\tsch " + strconv.Quote(importPath) + "\n")
	}
	b.WriteString(")\n\nfunc main() {\n")
	ref := "&sch." + typ + "{}"
	if importPath == "" {
		ref = "&" + typ + "{}"
	}
	b.WriteString("\tmeta := contract.AuthOf(" + ref + ")\n")
	b.WriteString("\tif err := json.NewEncoder(os.Stdout).Encode(meta); err != nil {\n\t\tos.Exit(1)\n\t}\n}\n")
	return b.String()
}

// RenderAuth generates zz_auth.go: a RegisterAuth whose parameter list is exactly the declared steps.
//
// Shaping the parameters after Steps is what this path buys over a hand-written WithAuth: **one
// handler short is a compile error** rather than a panic at startup — and an earlier form did not even
// panic, it just left the panel stuck on the missing step.
func RenderAuth(pkg string, meta AuthMeta) (string, error) {
	sig := []string{"h plugin.AuthHost"}
	assign := []string{}
	for _, s := range meta.Steps {
		switch s {
		case "start":
			sig = append(sig, "start func(plugin.Ctx) (*plugin.AuthChallenge, error)")
			assign = append(assign, "Start: start")
		case "poll":
			sig = append(sig, "poll func(ctx plugin.Ctx, authID string) (*plugin.AuthState, error)")
			assign = append(assign, "Poll: poll")
		case "submit":
			sig = append(sig, "submit func(ctx plugin.Ctx, authID, input string) error")
			assign = append(assign, "Submit: submit")
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// The authentication method is generated from the schema declaration.\n// Change it there, then regenerate.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n\t\"github.com/sokel-dev/sokel-plugin-sdk/plugin\"\n)\n\n")
	b.WriteString("// authMeta is this plugin's authentication declaration, exactly as declared.\n")
	b.WriteString("func authMeta() contract.AuthMeta {\n\treturn contract.AuthMeta{\n")
	b.WriteString("\t\tKind: contract." + kindConst(meta.Kind) + ",\n")
	if len(meta.Steps) > 0 {
		b.WriteString("\t\tSteps: " + renderSteps(meta.Steps) + ",\n")
	}
	if meta.Provider != "" {
		b.WriteString("\t\tProvider: " + strconv.Quote(meta.Provider) + ",\n")
		b.WriteString("\t\tScopes: " + renderStrings(meta.Scopes) + ",\n")
	}
	b.WriteString("\t}\n}\n\n")
	b.WriteString("// RegisterAuth declares how the credential is obtained and takes the implementation.\n")
	b.WriteString("// The parameter list follows the declared steps: missing one is a compile error, not a panel\n")
	b.WriteString("// that silently stalls at runtime.\n")
	fmt.Fprintf(&b, "func RegisterAuth(%s) {\n", strings.Join(sig, ", "))
	fmt.Fprintf(&b, "\th.SetAuthFlow(authMeta(), plugin.AuthHandlers{%s})\n}\n", strings.Join(assign, ", "))

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("the generated authentication code will not format (most likely a rendering bug): %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// renderSteps: a step is a named type (contract.AuthStep) and cannot be rendered as a bare string —
// emitting []string would leave the generated file unable to compile.
func renderSteps(ss []string) string {
	qs := make([]string, 0, len(ss))
	for _, s := range ss {
		qs = append(qs, "contract."+stepConst(s))
	}
	return "[]contract.AuthStep{" + strings.Join(qs, ", ") + "}"
}

func stepConst(step string) string {
	switch step {
	case "start":
		return "StepStart"
	case "poll":
		return "StepPoll"
	case "submit":
		return "StepSubmit"
	}
	return "AuthStep(" + strconv.Quote(step) + ")" // checkAuthMeta already rejected unknown steps; this is the fallback
}

func renderStrings(ss []string) string {
	qs := make([]string, 0, len(ss))
	for _, s := range ss {
		qs = append(qs, strconv.Quote(s))
	}
	return "[]string{" + strings.Join(qs, ", ") + "}"
}
