// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

// 凭证契约的生成：schema 声明 → Cred 类型 + 注册函数。
//
// 凭证是最后一块还留在「main 包里 struct + tag，运行时反射」上的契约——
// 操作与事件早已迁到声明式，凭证只是没跟着走。代价是实打实的：
// tag 写不出 enum 候选值，字段名拼错要等运行期静默绑空（不像操作有生成的类型兜着），
// 而且改凭证契约不触发 sokel-gen，与另外两样不是同一套心智。

import (
	"encoding/json"
	"fmt"
	"go/format"
	"strconv"
	"strings"
)

// credentialMethods：构成 contract.CredentialSchema 的方法集。
var credentialMethods = []string{"CredentialFields"}

// CredentialTypes 找出包内声明了凭证契约的类型（通常至多一个）。
func (p *Package) CredentialTypes() []string { return p.typesWith(credentialMethods) }

// LoadCredential 取出 schema 包里的凭证声明。
//
// 与操作/事件同一条路子：生成临时程序 import 该包、把声明摊平成 JSON 再读回来——
// 声明是**可执行代码**（builder 链式调用），源码级解析等于重新实现一遍 Go。
func LoadCredential(dir, importPath string, types []string) ([]Field, error) {
	if len(types) == 0 {
		return nil, nil
	}
	if len(types) > 1 {
		// 一个插件只有一份凭证契约。多份意味着声明写岔了，早说比生成一个随机挑的强。
		return nil, fmt.Errorf("凭证声明只能有一个，找到 %d 个: %s", len(types), strings.Join(types, ", "))
	}
	out, err := runLoader(dir, renderCredentialLoader(importPath, types[0]))
	if err != nil {
		return nil, err
	}
	var fields []Field
	if err := json.Unmarshal(out, &fields); err != nil {
		return nil, fmt.Errorf("解析凭证声明失败: %w\n%s", err, truncate(string(out), 300))
	}
	return fields, checkCredTypes(fields)
}

// credFieldTypes：凭证表单认识的字段类型。
//
// 与操作字段**不是同一套词汇**：那边是 string/number/boolean/…，这边是表单控件
// （见 web 的 CredFieldType）。用错了不会报错，只会静默退化成一个普通输入框——
// 声明了下拉却渲染出文本框，作者多半会以为是前端的 bug。
var credFieldTypes = map[string]string{
	"text": "", "secret": "", "select": "", "url": "", "secret-file": "", "header-list": "",
}

func checkCredTypes(fields []Field) error {
	for _, f := range fields {
		if _, ok := credFieldTypes[f.Type]; !ok {
			return fmt.Errorf("凭证字段 %q 的类型 %q 凭证表单不认识；请用 field.Text / field.Secret / field.Select（凭证的类型词汇是表单控件，不是 string/number 那一套）",
				f.Name, f.Type)
		}
	}
	return nil
}

func renderCredentialLoader(importPath, typ string) string {
	var b strings.Builder
	b.WriteString("// Generated by sokel-gen as a temporary program; deleted right after it runs.\npackage main\n\nimport (\n\t\"encoding/json\"\n\t\"os\"\n\n")
	b.WriteString("\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n")
	if importPath != "" {
		b.WriteString("\tsch " + strconv.Quote(importPath) + "\n")
	}
	b.WriteString(")\n\nfunc main() {\n")
	ref := "&sch." + typ + "{}"
	if importPath == "" {
		ref = "&" + typ + "{}"
	}
	b.WriteString("\tfields := contract.CredentialOf(" + ref + ")\n")
	b.WriteString("\tif err := json.NewEncoder(os.Stdout).Encode(fields); err != nil {\n\t\tos.Exit(1)\n\t}\n}\n")
	return b.String()
}

// RenderCredential 生成 zz_credential.go：Cred 类型 + RegisterCredential。
//
// 两样都要：
//   - Cred 类型给 sokel.CredentialAs[Cred](ctx) 用，字段名由声明定死，拼错编译期就报；
//   - 注册函数上报**声明的原样字段**，而不是回头反射 Cred——
//     反射产不出 enum 候选值，回头反射等于把刚拿到的表达力又丢掉。
//
// 参数取 plugin.CredentialHost 而非 *sokel.Plugin：生成物因此不 import go-sdk，
// 内核自带的契约声明（plugin-core 里）也能用同一个生成器，不会成环。
func RenderCredential(pkg string, sch SchemaRef, fields []Field) (string, error) {
	if len(fields) == 0 {
		return "", fmt.Errorf("凭证声明没有字段")
	}
	need := &imports{}
	body := renderCredStruct(fields, qual(sch.Name), need)

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// The credential contract is generated from the schema declaration.\n// Change it there, then regenerate.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n\t\"github.com/sokel-dev/sokel-plugin-sdk/plugin\"\n")
	if sch.Import != "" && need.schema {
		b.WriteString("\t" + strconv.Quote(sch.Import) + "\n")
	}
	b.WriteString(")\n\n")
	b.WriteString(body)

	b.WriteString("// credentialContract is the credential contract reported to the platform, exactly as declared.\n")
	b.WriteString("func credentialContract() []contract.Field {\n\treturn " + renderFields(fields, 1, "contract") + "\n}\n\n")
	b.WriteString("// RegisterCredential reports this plugin's credential contract. It replaces the older\n")
	b.WriteString("// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than\n")
	b.WriteString("// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.\n")
	b.WriteString("func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("生成的凭证代码无法格式化（多半是渲染有 bug）: %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// renderCredStruct：Cred 类型。带 sokel tag 是为了让 sokel.CredentialAs[Cred] 能按契约名绑定；
// 但**契约本身不从这些 tag 反射**（见 RenderCredential 的理由），tag 只是绑定用的键。
func renderCredStruct(fields []Field, schemaPkg string, need *imports) string {
	var b strings.Builder
	b.WriteString("// Cred is this plugin's credential contract, generated from the schema declaration.\n")
	b.WriteString("// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()[\"raw key\"]: a misspelled\n// raw key compiles fine and silently binds nothing.\n")
	b.WriteString("type Cred struct {\n")
	for _, f := range fields {
		tag := f.Name
		if !f.Required {
			tag += ",optional"
		}
		line := fmt.Sprintf("\t%s %s `sokel:%s", exportName(f.Name), goType(f, schemaPkg, "Cred", need, 1), strconv.Quote(tag))
		if f.Label != "" {
			line += " label:" + strconv.Quote(f.Label)
		}
		if f.Type == "secret" {
			line += ` secret:"true"`
		}
		if d, ok := f.Default.(string); ok && d != "" {
			line += " default:" + strconv.Quote(d) // 读取时的兜底（平台侧的默认值走契约字段）
		}
		b.WriteString(line + "`\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

// —— 认证流（凭证怎么拿到的）——

// authMethods：构成 contract.AuthSchema 的方法集（挂在凭证声明上，见 contract.AuthSchema）。
var authMethods = []string{"AuthMeta"}

// AuthTypes 找出声明了认证方式的类型。
func (p *Package) AuthTypes() []string { return p.typesWith(authMethods) }

// AuthMeta：认证声明的内容（与 contract.AuthMeta 同形，JSON 往返用）。
type AuthMeta struct {
	Kind     string   `json:"Kind"`
	Steps    []string `json:"Steps"`
	Provider string   `json:"Provider"`
	Scopes   []string `json:"Scopes"`
}

// LoadAuth 取出 schema 包里的认证声明。
func LoadAuth(dir, importPath string, types []string) (*AuthMeta, error) {
	if len(types) == 0 {
		return nil, nil
	}
	if len(types) > 1 {
		return nil, fmt.Errorf("认证声明只能有一个，找到 %d 个: %s", len(types), strings.Join(types, ", "))
	}
	out, err := runLoader(dir, renderAuthLoader(importPath, types[0]))
	if err != nil {
		return nil, err
	}
	var meta AuthMeta
	if err := json.Unmarshal(out, &meta); err != nil {
		return nil, fmt.Errorf("解析认证声明失败: %w\n%s", err, truncate(string(out), 300))
	}
	return &meta, checkAuthMeta(meta)
}

var authKinds = map[string]string{"qr": "AuthQR", "input": "AuthInput", "oauth": "AuthOAuth"}

func kindConst(kind string) string { return authKinds[kind] }

var authSteps = map[string]bool{"start": true, "poll": true, "submit": true}

// scopelessProviders：没有作用域这回事的家。
//
// Notion 的权限是用户在同意页上**勾哪些页面**，请求里压根没有 scope 参数——
// 按 Google 那套要求非空，等于让 Notion 插件填一个传上去会被拒的值。
// 平台侧有一份对应的判断（server/internal/credential/oauth.go 的 needScopes），两边加家时一起加。
var scopelessProviders = map[string]bool{"notion": true}

func checkAuthMeta(m AuthMeta) error {
	if authKinds[m.Kind] == "" {
		return fmt.Errorf("认证方式 %q 不认识（qr / input / oauth）", m.Kind)
	}
	for _, s := range m.Steps {
		if !authSteps[s] {
			return fmt.Errorf("认证步骤 %q 不认识（start / poll / submit）", s)
		}
	}
	switch m.Kind {
	case "oauth":
		// oauth 的 start/poll 由平台代答：声明步骤等于承诺一份永远不会被调用的实现。
		if len(m.Steps) > 0 {
			return fmt.Errorf("kind=oauth 不该声明 Steps —— start/poll 由平台代答（client_secret 在平台手里，插件构造不出同意页地址）")
		}
		if m.Provider == "" {
			return fmt.Errorf("kind=oauth 必须给 Provider（平台据它挑用哪家的换码方式）")
		}
		// 作用域由插件声明、平台不写死；留空对 Google 这类家等于要一个必然被拒的同意页。
		// 但**不是每家都有作用域**——见 scopelessProviders。
		if len(m.Scopes) == 0 && !scopelessProviders[m.Provider] {
			return fmt.Errorf("kind=oauth 必须给 Scopes（作用域由插件声明，平台不写死）")
		}
	default:
		// 少一步就是面板卡在那一步。这里拦住，作者就不必等扫完码才发现没有 poll。
		var has = map[string]bool{}
		for _, s := range m.Steps {
			has[s] = true
		}
		if !has["start"] || !has["poll"] {
			return fmt.Errorf("kind=%s 必须声明 start 与 poll 两步", m.Kind)
		}
	}
	return nil
}

func renderAuthLoader(importPath, typ string) string {
	var b strings.Builder
	b.WriteString("// Generated by sokel-gen as a temporary program; deleted right after it runs.\npackage main\n\nimport (\n\t\"encoding/json\"\n\t\"os\"\n\n")
	b.WriteString("\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n")
	if importPath != "" {
		b.WriteString("\tsch " + strconv.Quote(importPath) + "\n")
	}
	b.WriteString(")\n\nfunc main() {\n")
	ref := "&sch." + typ + "{}"
	if importPath == "" {
		ref = "&" + typ + "{}"
	}
	b.WriteString("\tmeta := contract.AuthOf(" + ref + ")\n")
	b.WriteString("\tif err := json.NewEncoder(os.Stdout).Encode(meta); err != nil {\n\t\tos.Exit(1)\n\t}\n}\n")
	return b.String()
}

// RenderAuth 生成 zz_auth.go：RegisterAuth（参数表 = 声明的那几步）。
//
// 参数表照 Steps 长是这条路相对手写 WithAuth 的实际收益：**少给一个 handler 是编译错**，
// 而不是启动时才 panic（更早的写法连 panic 都没有，面板会卡在缺的那一步）。
func RenderAuth(pkg string, meta AuthMeta) (string, error) {
	sig := []string{"h plugin.AuthHost"}
	assign := []string{}
	for _, s := range meta.Steps {
		switch s {
		case "start":
			sig = append(sig, "start func(plugin.Ctx) (*plugin.AuthChallenge, error)")
			assign = append(assign, "Start: start")
		case "poll":
			sig = append(sig, "poll func(ctx plugin.Ctx, authID string) (*plugin.AuthState, error)")
			assign = append(assign, "Poll: poll")
		case "submit":
			sig = append(sig, "submit func(ctx plugin.Ctx, authID, input string) error")
			assign = append(assign, "Submit: submit")
		}
	}

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// The authentication method is generated from the schema declaration.\n// Change it there, then regenerate.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n\t\"github.com/sokel-dev/sokel-plugin-sdk/plugin\"\n)\n\n")
	b.WriteString("// authMeta is this plugin's authentication declaration, exactly as declared.\n")
	b.WriteString("func authMeta() contract.AuthMeta {\n\treturn contract.AuthMeta{\n")
	b.WriteString("\t\tKind: contract." + kindConst(meta.Kind) + ",\n")
	if len(meta.Steps) > 0 {
		b.WriteString("\t\tSteps: " + renderSteps(meta.Steps) + ",\n")
	}
	if meta.Provider != "" {
		b.WriteString("\t\tProvider: " + strconv.Quote(meta.Provider) + ",\n")
		b.WriteString("\t\tScopes: " + renderStrings(meta.Scopes) + ",\n")
	}
	b.WriteString("\t}\n}\n\n")
	b.WriteString("// RegisterAuth declares how the credential is obtained and takes the implementation.\n")
	b.WriteString("// The parameter list follows the declared steps: missing one is a compile error, not a panel\n")
	b.WriteString("// that silently stalls at runtime.\n")
	fmt.Fprintf(&b, "func RegisterAuth(%s) {\n", strings.Join(sig, ", "))
	fmt.Fprintf(&b, "\th.SetAuthFlow(authMeta(), plugin.AuthHandlers{%s})\n}\n", strings.Join(assign, ", "))

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("生成的认证代码无法格式化（多半是渲染有 bug）: %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// renderSteps：步骤是有名类型（contract.AuthStep），不能当裸字符串渲染——
// 生成 []string 的话生成物直接编译不过。
func renderSteps(ss []string) string {
	qs := make([]string, 0, len(ss))
	for _, s := range ss {
		qs = append(qs, "contract."+stepConst(s))
	}
	return "[]contract.AuthStep{" + strings.Join(qs, ", ") + "}"
}

func stepConst(step string) string {
	switch step {
	case "start":
		return "StepStart"
	case "poll":
		return "StepPoll"
	case "submit":
		return "StepSubmit"
	}
	return "AuthStep(" + strconv.Quote(step) + ")" // checkAuthMeta 已拦下未知步骤，这里只是兜底
}

func renderStrings(ss []string) string {
	qs := make([]string, 0, len(ss))
	for _, s := range ss {
		qs = append(qs, strconv.Quote(s))
	}
	return "[]string{" + strings.Join(qs, ", ") + "}"
}
