// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// RenderEvents 生成事件侧的代码：payload 类型 + 声明函数 + typed 触发口。
//
// 事件此前只能命令式声明（DeclareEvent[T] + 反射），推事件更是完全无类型的
// ctx.Trigger(event, id, payload any)：事件名写错、payload 字段名写错都要等运行期。
// 生成之后两者都在编译期定死。
func RenderEvents(pkg string, sch SchemaRef, events []EventIO, common []string) (string, error) {
	if len(events) == 0 {
		return "", nil
	}
	sorted := append([]EventIO(nil), events...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var body strings.Builder
	need := &imports{}
	for _, e := range sorted {
		body.WriteString(renderEventPayload(e, qual(sch.Name), need))
	}

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// Event payload types and trigger functions are generated from the schema declaration.\n")
	b.WriteString("// Change an event there, then regenerate.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n\t\"github.com/sokel-dev/sokel-plugin-sdk/plugin\"\n")
	if sch.Import != "" {
		b.WriteString("\t" + strconv.Quote(sch.Import) + "\n")
	}
	b.WriteString(")\n\n")
	b.WriteString(body.String())

	// 声明函数：一次把全部事件与公共字段交给宿主。
	b.WriteString("// DeclareEvents hands this plugin's event contracts to the host.\n")
	b.WriteString("//\n// Common-field consistency was checked at **generation time** (each one must exist in every\n")
	b.WriteString("// event with the same type), so this cannot fail here — a real problem showed up at\n")
	b.WriteString("// go generate.\n")
	b.WriteString("func DeclareEvents(h plugin.EventHost) {\n")
	b.WriteString("\tevents := []contract.Event{\n")
	for _, e := range sorted {
		fmt.Fprintf(&b, "\t\tcontract.EventOf(&%s%s{}),\n", qual(sch.Name), e.TypeName)
	}
	b.WriteString("\t}\n\tfor _, e := range events {\n\t\th.DeclareEvent(e)\n\t}\n")
	if len(common) > 0 {
		b.WriteString("\tnames := []string{")
		for i, n := range common {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(strconv.Quote(n))
		}
		b.WriteString("}\n")
		b.WriteString("\tfields, _ := contract.ValidateCommonFields(events, names)\n")
		b.WriteString("\th.DeclareEventsCommon(fields, names)\n")
	}
	b.WriteString("}\n\n")

	// 每个事件一个 typed 触发口。
	for _, e := range sorted {
		name := exportName(e.ID)
		fmt.Fprintf(&b, "// Trigger%s pushes one %q event.\n", name, orDefaultStr(e.Label, e.ID))
		fmt.Fprintf(&b, "// eventID is the platform's deduplication key: re-pushing the same message triggers once.\n")
		fmt.Fprintf(&b, "func Trigger%s(ctx plugin.SourceCtx, eventID string, p *%sEvent) error {\n", name, name)
		fmt.Fprintf(&b, "\treturn ctx.Trigger(%s, eventID, p)\n}\n\n", strconv.Quote(e.ID))
	}

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("生成的事件代码无法格式化（多半是渲染有 bug）: %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

func renderEventPayload(e EventIO, schemaPkg string, need *imports) string {
	name := exportName(e.ID) + "Event"
	var b strings.Builder
	if e.Label != "" || e.Desc != "" {
		fmt.Fprintf(&b, "// %s is the payload of the %q event.\n", name, orDefaultStr(e.Label, e.ID))
		if e.Desc != "" {
			fmt.Fprintf(&b, "// %s\n", e.Desc)
		}
	}
	fmt.Fprintf(&b, "type %s struct {\n", name)
	for _, f := range e.Fields {
		fmt.Fprintf(&b, "\t%s %s `json:%s sokel:%s`\n",
			exportName(f.Name), goType(f, schemaPkg, name, need, 1), strconv.Quote(f.Name), strconv.Quote(f.Name))
	}
	b.WriteString("}\n\n")
	return b.String()
}

func orDefaultStr(s, def string) string {
	if s == "" {
		return def
	}
	return s
}
