// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
)

// LoadDeclarations reads back **the declared content** of every operation in the schema package.
//
// A declaration is executable Go code (chained builder calls), not a tag string — so the way to read
// it is to generate a throwaway program that imports the package, calls sokel.OperationOf and prints
// JSON, then read that back. This is far more reliable than parsing the AST: builders may contain
// loops, constants and helper functions, all of which source-level parsing would have to reimplement,
// whereas running the code once gets everything right.
//
// dir is the schema package's directory (the throwaway program goes in .sokelgen/ underneath it and is
// deleted afterwards — it has to be inside the same module to import the package); importPath is that
// package's import path.
func LoadDeclarations(dir, importPath string, types []string) ([]OpIO, error) {
	if len(types) == 0 {
		return nil, fmt.Errorf("there are no Schema types to load")
	}
	out, err := runLoader(dir, renderLoader(importPath, types))
	if err != nil {
		return nil, err
	}

	var ops []struct {
		ID      string  `json:"id"`
		Label   string  `json:"label"`
		Desc    string  `json:"desc"`
		Stream  bool    `json:"stream"`
		Inputs  []Field `json:"inputs"`
		Outputs []Field `json:"outputs"`
	}
	if err := json.Unmarshal(out, &ops); err != nil {
		return nil, fmt.Errorf("failed to parse the declaration output: %w\n%s", err, truncate(string(out), 300))
	}

	res := make([]OpIO, 0, len(ops))
	for i, o := range ops {
		res = append(res, OpIO{
			OpID:       o.ID,
			Label:      o.Label,
			Desc:       o.Desc,
			SchemaType: types[i], // the registration code reads the contract via sokel.OperationOf(&schema.X{})
			// Everything generated is named after **the operation id**: On/Emitter always were, while In/Out
			// used to follow the schema type name — indistinguishable while the two agree, but the moment
			// they differ (type Stream with id "egress_stream") the generated code simply does not compile.
			// One source for names, and one only.
			InType:  exportName(o.ID) + "In",
			OutType: exportName(o.ID) + "Out",
			Stream:  o.Stream,
			Inputs:  o.Inputs,
			Outputs: o.Outputs,
		})
	}
	return res, nil
}

// renderLoader assembles the throwaway program. It always takes an address with &T{}: a value
// receiver's method set is included in the pointer's, so value and pointer declarations need no
// separate handling.
//
// It imports only plugin-core/contract and never the SDK, so that the kernel's own contract
// declarations (httpcore/plugin, llmcore/plugin) can be generated too without plugin-core having to
// depend on the SDK in return. When the declarations are in the same package, importPath is empty and
// the types are referenced directly.
// runLoader writes the declaration-reading program into .sokelgen/, runs it once and returns its
// stdout.
func runLoader(dir, src string) ([]byte, error) {
	tmpDir := filepath.Join(dir, ".sokelgen")
	if err := os.MkdirAll(tmpDir, 0o755); err != nil {
		return nil, fmt.Errorf("failed to create the temporary directory: %w", err)
	}
	defer os.RemoveAll(tmpDir)
	if err := os.WriteFile(filepath.Join(tmpDir, "main.go"), []byte(src), 0o644); err != nil {
		return nil, fmt.Errorf("failed to write the temporary program: %w", err)
	}
	cmd := exec.Command("go", "run", "./.sokelgen")
	cmd.Dir = dir
	var stderr strings.Builder
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		// Pass compile and validation errors through verbatim — what the author needs to see is the problem
		// in their own schema, not the words "generation failed".
		return nil, fmt.Errorf("failed to run the schema to read its declarations: %w\n%s", err, strings.TrimSpace(stderr.String()))
	}
	return out, nil
}

func renderLoader(importPath string, types []string) string {
	var b strings.Builder
	b.WriteString("// Generated by sokel-gen as a temporary program; deleted right after it runs.\npackage main\n\nimport (\n\t\"encoding/json\"\n\t\"os\"\n\n")
	b.WriteString("\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n")
	b.WriteString("\tsch " + strconv.Quote(importPath) + "\n)\n\n")
	b.WriteString("func main() {\n\tops := []contract.Operation{\n")
	for _, t := range types {
		b.WriteString("\t\tcontract.OperationOf(&sch." + t + "{}),\n")
	}
	b.WriteString("\t}\n\tif err := json.NewEncoder(os.Stdout).Encode(ops); err != nil {\n\t\tos.Exit(1)\n\t}\n}\n")
	return b.String()
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// EventIO is one event's declared content, used to generate its payload type and typed trigger.
type EventIO struct {
	ID     string  `json:"id"`
	Label  string  `json:"label"`
	Desc   string  `json:"desc"`
	Fields []Field `json:"fields"`
	// TypeName is the Go type that declares it, used to generate contract.EventOf(&schema.X{}).
	TypeName string `json:"-"`
}

// LoadEvents reads the event declarations and common fields out of the schema package.
//
// Same method as LoadDeclarations: the declarations are executable code, and running them beats
// parsing the AST. commonTypes holds at most one entry (the type that declares CommonFields).
func LoadEvents(dir, importPath string, eventTypes, commonTypes []string) ([]EventIO, []string, error) {
	if len(eventTypes) == 0 {
		return nil, nil, nil
	}
	out, err := runLoader(dir, renderEventLoader(importPath, eventTypes, commonTypes))
	if err != nil {
		return nil, nil, err
	}
	var res struct {
		Events []EventIO `json:"events"`
		Common []string  `json:"common"`
	}
	if err := json.Unmarshal(out, &res); err != nil {
		return nil, nil, fmt.Errorf("failed to parse the event declarations: %w\n%s", err, truncate(string(out), 300))
	}
	for i := range res.Events {
		res.Events[i].TypeName = eventTypes[i]
	}
	return res.Events, res.Common, nil
}

func renderEventLoader(importPath string, events, commons []string) string {
	var b strings.Builder
	b.WriteString("// Generated by sokel-gen as a temporary program; deleted right after it runs.\npackage main\n\nimport (\n\t\"encoding/json\"\n\t\"os\"\n\n")
	b.WriteString("\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n")
	b.WriteString("\tsch " + strconv.Quote(importPath) + "\n)\n\n")
	b.WriteString("func main() {\n\tevents := []contract.Event{\n")
	for _, t := range events {
		b.WriteString("\t\tcontract.EventOf(&sch." + t + "{}),\n")
	}
	b.WriteString("\t}\n\tvar common []string\n")
	for _, t := range commons {
		b.WriteString("\tcommon = append(common, (&sch." + t + "{}).CommonFields()...)\n")
	}
	// Common-field consistency is checked right here: failing at generation time is far earlier than
	// having the platform reject the registration handshake at runtime.
	b.WriteString("\tif _, err := contract.ValidateCommonFields(events, common); err != nil {\n")
	b.WriteString("\t\tos.Stderr.WriteString(err.Error())\n\t\tos.Exit(1)\n\t}\n")
	b.WriteString("\tif err := json.NewEncoder(os.Stdout).Encode(map[string]any{\"events\": events, \"common\": common}); err != nil {\n\t\tos.Exit(1)\n\t}\n}\n")
	return b.String()
}
