// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

// The reverse direction: a Go schema/ declaration becomes a language-neutral sokel.yaml.
//
// The point is **copying a contract across languages**: a Python or Node author implementing the same
// plugin (or learning from an existing first-party one) need not read the Go builder API, and the Go
// declaration need not become the de facto standard. The exported YAML is the §5 contract itself, and
// feeding it back to sokel-gen generates another language.

import (
	"encoding/json"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// ManifestFrom assembles a manifest from a Go declaration: operations, credential, events and auth.
func ManifestFrom(name string, ops []OpIO, cred []Field, auth *AuthMeta, events []EventIO, common []string) *Manifest {
	m := &Manifest{Plugin: PluginDecl{Name: name}}
	for _, op := range ops {
		m.Operations = append(m.Operations, OperationDecl{
			ID: op.OpID, Label: op.Label, Desc: op.Desc, Stream: op.Stream,
			Inputs: nonNil(op.Inputs), Outputs: nonNil(op.Outputs),
		})
	}
	if len(cred) > 0 || auth != nil {
		c := &CredentialDecl{Fields: cred}
		if auth != nil {
			c.Auth = &AuthDecl{Kind: auth.Kind, Provider: auth.Provider, Scopes: auth.Scopes}
		}
		m.Credential = c
	}
	for _, e := range events {
		m.Events = append(m.Events, EventDecl{ID: e.ID, Label: e.Label, Desc: e.Desc, Fields: nonNil(e.Fields)})
	}
	m.EventsCommon = common
	return m
}

// RenderManifestYAML renders a manifest as sokel.yaml.
//
// It goes struct -> JSON -> YAML rather than straight to yaml.Marshal, because Field carries only json
// tags: handing it to yaml.v3 directly yields lowercased keys (valuetype, timeoutsec), and reading that
// YAML back in **fails to recognise them** — a silent broken round trip.
func RenderManifestYAML(m *Manifest) (string, error) {
	b, err := json.Marshal(m)
	if err != nil {
		return "", err
	}
	var node any
	if err := json.Unmarshal(b, &node); err != nil {
		return "", err
	}
	top, ok := node.(map[string]any)
	if !ok {
		return "", fmt.Errorf("the manifest is not an object (this should not happen)")
	}
	// Restore the key spellings used in the protocol document: whoever reads this has most likely just
	// finished plugin-wire-protocol.md
	for from, to := range map[string]string{"eventsCommon": "events_common", "docUrl": "doc_url"} {
		if v, ok := top[from]; ok {
			delete(top, from)
			top[to] = v
		}
	}

	var out strings.Builder
	out.WriteString("# Generated by sokel-gen export yaml: the language-neutral form of this plugin's contract.\n")
	out.WriteString("# Use it as the starting point for implementing the same plugin elsewhere:\n")
	out.WriteString("#   sokel-gen generate -lang python|ts\n")
	// Emit section by section rather than dumping the whole map: yaml.v3 sorts map keys **alphabetically**,
	// which would drop plugin below operations — and in a declaration meant for people to read, the
	// alphabet does not get to decide the order.
	for _, key := range []string{"plugin", "capabilities", "credential", "events_common", "events", "operations", "codegen"} {
		v, ok := top[key]
		if !ok || isEmpty(v) {
			continue
		}
		var sec strings.Builder
		enc := yaml.NewEncoder(&sec)
		enc.SetIndent(2)
		if err := enc.Encode(map[string]any{key: v}); err != nil {
			return "", err
		}
		if err := enc.Close(); err != nil {
			return "", err
		}
		out.WriteString("\n" + sec.String())
	}
	return out.String(), nil
}

func isEmpty(v any) bool {
	switch t := v.(type) {
	case nil:
		return true
	case []any:
		return len(t) == 0
	case map[string]any:
		return len(t) == 0
	case string:
		return t == ""
	}
	return false
}

// ExportManifestJSON exports a manifest as the contract JSON of the registration handshake (§5 of the
// protocol). This is the same data embedded in all three languages' output — it is what the golden file
// compares.
func ExportManifestJSON(m *Manifest, doc string) ([]byte, error) {
	cj, err := contractJSON(m, doc)
	if err != nil {
		return nil, err
	}
	out, err := json.MarshalIndent(cj, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("failed to serialise the contract: %w", err)
	}
	return out, nil
}
