// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// RenderPython renders the same IR as pydantic models.
//
// It is both the first consumer of multi-language generation and the way to **check the IR is
// sufficient**, while existing plugins have not yet frozen it.
//
// GoType takes on a different job here: on the Go side it means "reuse the author's existing type",
// whereas Python has no existing type, so it becomes "give this struct a name instead of generating an
// anonymous nested class". A given name is defined once.
func RenderPython(ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("there are no operations to generate")
	}
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	// Collect every named struct first — they may nest and may be referenced from several places — and
	// define each of them once.
	named := map[string][]Field{}
	for _, op := range sorted {
		collectNamed(op.Inputs, named)
		collectNamed(op.Outputs, named)
	}

	var b strings.Builder
	b.WriteString("# Code generated by sokel-gen. DO NOT EDIT.\n#\n")
	b.WriteString("# Generated from the plugin's schema declaration (the same contract also generates the Go types).\n")
	b.WriteString("# Change a field in the schema, then regenerate.\n\n")
	b.WriteString("from typing import Any\n\nfrom pydantic import BaseModel\n\n\n")

	// Emit the named structs sorted by name so that generation is deterministic.
	names := make([]string, 0, len(named))
	for n := range named {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		writeModel(&b, n, named[n])
	}

	for _, op := range sorted {
		writeModel(&b, exportName(op.OpID)+"In", op.Inputs)
		writeModel(&b, exportName(op.OpID)+"Out", op.Outputs)
	}
	return b.String(), nil
}

// collectNamed recursively collects named structs (a non-empty GoType with fields).
func collectNamed(fields []Field, out map[string][]Field) {
	for _, f := range fields {
		if f.GoType != "" && len(f.Fields) > 0 && !isIntGoType(f.GoType) {
			if _, seen := out[f.GoType]; !seen {
				out[f.GoType] = f.Fields
			}
		}
		collectNamed(f.Fields, out)
		if f.ValueType != nil {
			collectNamed([]Field{*f.ValueType}, out)
		}
		for _, v := range f.OneOf {
			// The branches themselves have to become models too: Python has real union types, and referring to
			// concrete models is the whole point.
			if v.GoType != "" && len(v.Fields) > 0 {
				if _, seen := out[v.GoType]; !seen {
					out[v.GoType] = v.Fields
				}
			}
			collectNamed(v.Fields, out)
		}
	}
}

func writeModel(b *strings.Builder, name string, fields []Field) {
	fmt.Fprintf(b, "class %s(BaseModel):\n", name)
	if len(fields) == 0 {
		b.WriteString("    pass\n\n\n")
		return
	}
	for _, f := range fields {
		t, def := pyType(f), pyDefault(f)
		// Optional with no default has to be written `T | None`, or pydantic v2 treats None as a validation
		// error. With a default it is unnecessary: the default already states the type.
		if !f.Required && f.Default == nil {
			t += " | None"
		}
		fmt.Fprintf(b, "    %s: %s%s\n", pyName(f.Name), t, def)
	}
	b.WriteString("\n\n")
}

func pyType(f Field) string {
	switch f.Type {
	case "number":
		if isIntGoType(f.GoType) { // the integer hint carries through to Python as well
			return "int"
		}
		return "float"
	case "boolean":
		return "bool"
	case "file":
		return "Any" // the Python representation of a file is up to the SDK; treat it as opaque for now
	case "json":
		// A structural union is exactly Python's `A | B`; no wrapper is needed as in Go.
		if len(f.OneOf) > 0 {
			return pyUnion(f.OneOf)
		}
		// opaque: open-ended keys but still an object (type=json in the contract). Optional[dict] is more
		// accurate than a bare Any.
		if f.Opaque {
			return "dict[str, Any]"
		}
		if f.GoType != "" && len(f.Fields) > 0 {
			return f.GoType
		}
		if f.ValueType != nil {
			return "dict[str, " + pyType(*f.ValueType) + "]"
		}
		return "Any"
	case "array":
		// A union element (field.ArrayOf) becomes list[A | B].
		if len(f.OneOf) > 0 {
			return "list[" + pyUnion(f.OneOf) + "]"
		}
		if f.Opaque {
			return "list[Any]"
		}
		if f.GoType != "" && len(f.Fields) > 0 {
			return "list[" + f.GoType + "]"
		}
		if isIntGoType(f.GoType) {
			return "list[int]"
		}
		if f.ItemType != "" {
			return "list[" + pyScalar(f.ItemType) + "]"
		}
		return "list[Any]"
	}
	return "str" // string / text / enum
}

// pyUnion renders oneOf branches as a Python union type. When a branch's shape cannot be stated, the
// whole thing falls back to Any: `A | Any` is equivalent to Any, and spelling it out only misleads.
func pyUnion(vs []OneOfVariant) string {
	parts := make([]string, 0, len(vs))
	for _, v := range vs {
		if v.GoType == "" || len(v.Fields) == 0 {
			return "Any"
		}
		if v.Type == "array" {
			parts = append(parts, "list["+v.GoType+"]")
			continue
		}
		parts = append(parts, v.GoType)
	}
	if len(parts) == 0 {
		return "Any"
	}
	return strings.Join(parts, " | ")
}

func pyScalar(t string) string {
	switch t {
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "file":
		return "Any" // a file list becomes list[Any]: the Python file representation is up to the SDK, as for a single file
	}
	return "str"
}

// pyDefault emits the default when there is one, and None for an optional field without one, avoiding
// the syntax error of a required field following an optional one.
func pyDefault(f Field) string {
	if f.Default != nil {
		switch v := f.Default.(type) {
		case string:
			return " = " + strconv.Quote(v)
		case bool:
			if v { // Python capitalises True/False
				return " = True"
			}
			return " = False"
		case float64:
			return " = " + strconv.FormatFloat(v, 'g', -1, 64)
		}
	}
	if !f.Required {
		return " = None"
	}
	return ""
}

// pyName uses the contract name as-is (it is already snake_case, which is Python's convention), adding
// a trailing underscore when it collides with a keyword.
func pyName(s string) string {
	switch s {
	case "class", "def", "import", "from", "return", "None", "True", "False", "lambda", "global", "pass":
		return s + "_"
	}
	return s
}
