// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// RenderPython 把同一份 IR 渲染成 pydantic 模型。
//
// 这既是多语言生成的第一个消费者，也是**验证 IR 够不够用**的手段——趁存量插件还没锁死它。
//
// GoType 在这里换了个用途：Go 侧它意味着「复用作者已有的类型」，Python 侧没有既存类型，
// 它的作用变成「给这个结构一个名字，而不是生成匿名嵌套类」。同名类型只定义一次。
func RenderPython(ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("没有可生成的操作")
	}
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	// 先把所有具名结构收齐（可能嵌套、可能被多处引用），每个只定义一次。
	named := map[string][]Field{}
	for _, op := range sorted {
		collectNamed(op.Inputs, named)
		collectNamed(op.Outputs, named)
	}

	var b strings.Builder
	b.WriteString("# Code generated by sokel-gen. DO NOT EDIT.\n#\n")
	b.WriteString("# Generated from the plugin's schema declaration (the same contract also generates the Go types).\n")
	b.WriteString("# Change a field in the schema, then regenerate.\n\n")
	b.WriteString("from typing import Any\n\nfrom pydantic import BaseModel\n\n\n")

	// 具名结构按名字排序输出，保证生成确定性。
	names := make([]string, 0, len(named))
	for n := range named {
		names = append(names, n)
	}
	sort.Strings(names)
	for _, n := range names {
		writeModel(&b, n, named[n])
	}

	for _, op := range sorted {
		writeModel(&b, exportName(op.OpID)+"In", op.Inputs)
		writeModel(&b, exportName(op.OpID)+"Out", op.Outputs)
	}
	return b.String(), nil
}

// collectNamed 递归收集带名字的结构（GoType 非空且有字段）。
func collectNamed(fields []Field, out map[string][]Field) {
	for _, f := range fields {
		if f.GoType != "" && len(f.Fields) > 0 && !isIntGoType(f.GoType) {
			if _, seen := out[f.GoType]; !seen {
				out[f.GoType] = f.Fields
			}
		}
		collectNamed(f.Fields, out)
		if f.ValueType != nil {
			collectNamed([]Field{*f.ValueType}, out)
		}
		for _, v := range f.OneOf {
			// 分支本身也要成为模型——Python 有真联合类型，引用得到具体模型才有意义。
			if v.GoType != "" && len(v.Fields) > 0 {
				if _, seen := out[v.GoType]; !seen {
					out[v.GoType] = v.Fields
				}
			}
			collectNamed(v.Fields, out)
		}
	}
}

func writeModel(b *strings.Builder, name string, fields []Field) {
	fmt.Fprintf(b, "class %s(BaseModel):\n", name)
	if len(fields) == 0 {
		b.WriteString("    pass\n\n\n")
		return
	}
	for _, f := range fields {
		t, def := pyType(f), pyDefault(f)
		// 非必填且无默认值 → 类型要写成 `T | None`，否则 pydantic v2 会把 None 判为校验错。
		// 有默认值的不必：默认值本身已经说明了类型。
		if !f.Required && f.Default == nil {
			t += " | None"
		}
		fmt.Fprintf(b, "    %s: %s%s\n", pyName(f.Name), t, def)
	}
	b.WriteString("\n\n")
}

func pyType(f Field) string {
	switch f.Type {
	case "number":
		if isIntGoType(f.GoType) { // 整数提示同样传导到 Python
			return "int"
		}
		return "float"
	case "boolean":
		return "bool"
	case "file":
		return "Any" // 文件的 Python 侧表示待 SDK 定义，先按不透明处理
	case "json":
		// 结构联合：Python 的 `A | B` 就是它，不必像 Go 那样包一层。
		if len(f.OneOf) > 0 {
			return pyUnion(f.OneOf)
		}
		// opaque：键值不定但仍是对象（契约 type=json）。Optional[dict] 比裸 Any 准确。
		if f.Opaque {
			return "dict[str, Any]"
		}
		if f.GoType != "" && len(f.Fields) > 0 {
			return f.GoType
		}
		if f.ValueType != nil {
			return "dict[str, " + pyType(*f.ValueType) + "]"
		}
		return "Any"
	case "array":
		// 元素是联合（field.ArrayOf）：list[A | B]。
		if len(f.OneOf) > 0 {
			return "list[" + pyUnion(f.OneOf) + "]"
		}
		if f.Opaque {
			return "list[Any]"
		}
		if f.GoType != "" && len(f.Fields) > 0 {
			return "list[" + f.GoType + "]"
		}
		if isIntGoType(f.GoType) {
			return "list[int]"
		}
		if f.ItemType != "" {
			return "list[" + pyScalar(f.ItemType) + "]"
		}
		return "list[Any]"
	}
	return "str" // string / text / enum
}

// pyUnion 把 oneOf 分支渲染成 Python 联合类型。
// 分支形状说不清时整体退回 Any——`A | Any` 与 Any 等价，写出来反而误导。
func pyUnion(vs []OneOfVariant) string {
	parts := make([]string, 0, len(vs))
	for _, v := range vs {
		if v.GoType == "" || len(v.Fields) == 0 {
			return "Any"
		}
		if v.Type == "array" {
			parts = append(parts, "list["+v.GoType+"]")
			continue
		}
		parts = append(parts, v.GoType)
	}
	if len(parts) == 0 {
		return "Any"
	}
	return strings.Join(parts, " | ")
}

func pyScalar(t string) string {
	switch t {
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "file":
		return "Any" // 文件列表 list[Any]：Python 侧文件表示待 SDK 定义（与单 file 一致）
	}
	return "str"
}

// pyDefault：有默认值就带上；没有但非必填时给 None，避免「必填字段排在可选之后」的语法错。
func pyDefault(f Field) string {
	if f.Default != nil {
		switch v := f.Default.(type) {
		case string:
			return " = " + strconv.Quote(v)
		case bool:
			if v { // Python 的 True/False 首字母大写
				return " = True"
			}
			return " = False"
		case float64:
			return " = " + strconv.FormatFloat(v, 'g', -1, 64)
		}
	}
	if !f.Required {
		return " = None"
	}
	return ""
}

// pyName：契约里的名字直接用（已是 snake_case，正是 Python 惯例）；
// 撞上关键字时加下划线后缀。
func pyName(s string) string {
	switch s {
	case "class", "def", "import", "from", "return", "None", "True", "False", "lambda", "global", "pass":
		return s + "_"
	}
	return s
}
