// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// RenderRegister generates the OnXxx registration function for each operation, joining the schema's
// declaration, the generated In/Out types and the author's handler.
//
// The signature is fully concrete, and **this is where type safety lives**: sokel.RegisterOp takes the
// generic-free (raw, Sink) form, and this generated layer decodes into In, calls the concretely typed
// handler and hands Out back to the Sink.
//
// The contract comes from sokel.OperationOf(&schema.X{}) rather than copying the fields into the
// generated file: a copy goes stale whenever the schema changes without regeneration, and that kind of
// divergence is very hard to spot.
//
// Inputs go through contract.BindInput rather than json.Unmarshal, because the former binds by sokel
// tag **recursively**. With json.Unmarshal, snake_case contract fields inside nested structs bind to
// nothing, silently and without an error (Go's case-insensitive matching does not cross an underscore,
// so doc_id never reaches DocID).
func RenderRegister(pkg string, sch SchemaRef, ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("there are no operations to generate")
	}
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.\n")
	b.WriteString("// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the\n")
	b.WriteString("// platform's in-process host each implement it, so the same handler runs under either.\n")
	b.WriteString("// Change an operation in the schema declaration, then regenerate.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"encoding/json\"\n\n\t\"github.com/sokel-dev/sokel-plugin-sdk/contract\"\n\t\"github.com/sokel-dev/sokel-plugin-sdk/plugin\"\n")
	if sch.Import != "" {
		b.WriteString("\t" + strconv.Quote(sch.Import) + "\n")
	}
	b.WriteString(")\n\n")

	for _, op := range sorted {
		name := exportName(op.OpID)
		if op.Stream {
			renderStreamOp(&b, name, op, qual(sch.Name))
			continue
		}
		renderUnaryOp(&b, name, op, qual(sch.Name))
	}

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("the generated code will not format (most likely a rendering bug): %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// Non-streaming: one result per call, the most common shape.
// qual is the schema package prefix. It is empty within the same package, so the output is &Chat{}
// rather than &schema.Chat{}.
func qual(name string) string {
	if name == "" {
		return ""
	}
	return name + "."
}

func renderUnaryOp(b *strings.Builder, name string, op OpIO, schemaPkg string) {
	fmt.Fprintf(b, "// On%s registers the implementation of %q.\n", name, op.OpID)
	fmt.Fprintf(b, "func On%s(h plugin.Host, fn func(plugin.Ctx, *%s) (*%s, error)) {\n", name, op.InType, op.OutType)
	fmt.Fprintf(b, "\th.Register(contract.OperationOf(&%s%s{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {\n", schemaPkg, op.SchemaType)
	fmt.Fprintf(b, "\t\tvar in %s\n", op.InType)
	b.WriteString("\t\tif err := contract.BindInput(raw, &in); err != nil {\n\t\t\treturn err\n\t\t}\n")
	b.WriteString("\t\tres, err := fn(ctx, &in)\n\t\tif err != nil {\n\t\t\treturn err\n\t\t}\n")
	// A nil result emits nothing: a handler may be side-effect-only and need not invent an output
	b.WriteString("\t\tif res != nil {\n\t\t\tout.Vars(res)\n\t\t}\n\t\treturn nil\n")
	b.WriteString("\t})\n}\n\n")
}

// Streaming: the handler receives a typed emitter and may send many times.
func renderStreamOp(b *strings.Builder, name string, op OpIO, schemaPkg string) {
	em := name + "Emitter"
	fmt.Fprintf(b, "// %s is the typed emitter for %q: the library's Sink takes any, this layer pins the type.\n", em, op.OpID)
	fmt.Fprintf(b, "type %s struct{ sink plugin.Sink }\n\n", em)
	fmt.Fprintf(b, "// Vars emits one frame of typed output variables (they flow downstream).\n")
	fmt.Fprintf(b, "func (e *%s) Vars(v *%s) { e.sink.Vars(v) }\n\n", em, op.OutType)
	fmt.Fprintf(b, "// Text emits human-readable text (display / tracing).\n")
	fmt.Fprintf(b, "func (e *%s) Text(s string) { e.sink.Text(s) }\n\n", em)
	fmt.Fprintf(b, "// JSON emits structured JSON (display / tracing).\n")
	fmt.Fprintf(b, "func (e *%s) JSON(v any) { e.sink.JSON(v) }\n\n", em)

	fmt.Fprintf(b, "// On%s registers the implementation of %q (streaming).\n", name, op.OpID)
	fmt.Fprintf(b, "func On%s(h plugin.Host, fn func(plugin.Ctx, *%s, *%s) error) {\n", name, op.InType, em)
	fmt.Fprintf(b, "\th.Register(contract.OperationOf(&%s%s{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {\n", schemaPkg, op.SchemaType)
	fmt.Fprintf(b, "\t\tvar in %s\n", op.InType)
	b.WriteString("\t\tif err := contract.BindInput(raw, &in); err != nil {\n\t\t\treturn err\n\t\t}\n")
	fmt.Fprintf(b, "\t\treturn fn(ctx, &in, &%s{sink: out})\n", em)
	b.WriteString("\t})\n}\n\n")
}
