// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

// Renders the typed shell of a Python plugin from sokel.yaml: pydantic models, registration functions
// and triggers.
//
// Why Python goes through codegen too, rather than reading the YAML at runtime: a contract is **a
// declaration**, and a declaration is worth having because mistakes surface as you make them. Reading
// the YAML at runtime means a misspelled field blows up only when the platform calls, and the
// implementation still receives a bare dict — exactly what this SDK exists to eliminate. Generated, a
// misspelled in_.project is a red squiggle in the IDE rather than one failed call in production.

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// modelSet holds the named structs gathered while rendering, ordered **dependencies first**.
type modelSet struct {
	order    []string
	fields   map[string][]Field
	rendered map[string]string
}

func newModelSet() *modelSet {
	return &modelSet{fields: map[string][]Field{}, rendered: map[string]string{}}
}

func (s *modelSet) setRendered(name, src string) { s.rendered[name] = src }

// ensure registers a named struct, returning the name unchanged if it already exists so that a given
// struct is defined once. render runs before the append, so child structs always precede their parents
// and Python never needs a forward reference.
func (s *modelSet) ensure(name string, fields []Field, render func()) string {
	if _, ok := s.fields[name]; ok {
		return name
	}
	s.fields[name] = fields
	render()
	s.order = append(s.order, name)
	return name
}

// RenderPythonPlugin generates the whole typed shell on the Python side.
func RenderPythonPlugin(m *Manifest, doc string) (string, error) {
	cj, err := contractJSON(m, doc)
	if err != nil {
		return "", err
	}
	models := newModelSet()
	var body strings.Builder

	// The credential gets a model and a reader function. A misspelled bare ctx.credential["api_key"]
	// silently binds nothing, which is how credential fields typically fail — especially for event
	// sources, whose cursor and session both live in the credential.
	if m.Credential != nil && len(m.Credential.Fields) > 0 {
		// Every field of the credential model **carries a default**, even those the contract marks required.
		// required means "the user must fill this in on the form", not "this is present on every call": a
		// freshly created credential, one that has not logged in yet, or an event-source instance with no
		// credential bound all arrive as an empty table. Generating them as required would make
		// `Credential(**ctx.credential)` raise a validation error at the one place in a plugin that must not
		// blow up — as observed, an event source failed on its very first start exactly there.
		body.WriteString(pyModel("Credential", "Credential fields (the platform injects them with every call; a plugin never stores them).\n\nEvery field may be absent: `required` means \"the UI insists on it\", not \"every call carries it\".",
			optionalFields(m.Credential.Fields), models, "Credential"))
		body.WriteString("def credential(ctx: Any) -> Credential:\n")
		body.WriteString("    \"\"\"Read this call's credential into a typed object (works for both operation and source ctx).\"\"\"\n")
		body.WriteString("    return ctx.credential_as(Credential)\n\n\n")
	}

	ops := append([]OperationDecl(nil), m.Operations...)
	sort.Slice(ops, func(i, j int) bool { return ops[i].ID < ops[j].ID })
	for _, op := range ops {
		name := exportName(op.ID)
		body.WriteString(pyModel(name+"In", opComment(op, "Inputs"), op.Inputs, models, name+"In"))
		body.WriteString(pyModel(name+"Out", opComment(op, "Outputs"), op.Outputs, models, name+"Out"))
		body.WriteString(pyRegisterFn(op, name))
	}

	events := append([]EventDecl(nil), m.Events...)
	sort.Slice(events, func(i, j int) bool { return events[i].ID < events[j].ID })
	for _, e := range events {
		name := exportName(e.ID) + "Event"
		body.WriteString(pyModel(name, "Payload of the "+strconv.Quote(orDefaultStr(e.Label, e.ID))+" event", e.Fields, models, name))
		fn := "trigger_" + e.ID
		fmt.Fprintf(&body, "async def %s(ctx: SourceCtx, event_id: str, payload: %s) -> None:\n", fn, name)
		fmt.Fprintf(&body, "    \"\"\"Push one %q event. event_id is the idempotency key: re-pushing the same upstream message triggers once.\"\"\"\n", orDefaultStr(e.Label, e.ID))
		fmt.Fprintf(&body, "    await ctx.trigger(%s, event_id, payload)\n\n\n", jsonQuote(e.ID))
	}

	var b strings.Builder
	b.WriteString("# Code generated by sokel-gen. DO NOT EDIT.\n#\n")
	b.WriteString("# The contract is declared in sokel.yaml — change a field there and re-run `sokel-gen generate`.\n")
	b.WriteString("# Edits to this file are lost on the next generation.\n\n")
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("from typing import Any, Awaitable, Callable, Dict, List, Literal, Optional, Union\n\n")
	b.WriteString("import inspect\n\n")
	b.WriteString("from pydantic import BaseModel\n")
	b.WriteString("from sokel import Ctx, Emitter, File, Plugin, SourceCtx\n\n")
	b.WriteString("__all__ = [\n")
	for _, n := range pyExports(m, models) {
		b.WriteString("    " + jsonQuote(n) + ",\n")
	}
	b.WriteString("]\n\n")
	b.WriteString("# The contract reported to the platform (equivalent to sokel.yaml; all three languages embed this same JSON).\n")
	b.WriteString("CONTRACT: Dict[str, Any] = " + renderPyLiteral(cj, 0) + "\n\n\n")

	// Named structs are emitted before the models that reference them
	var pre strings.Builder
	for _, name := range models.order {
		pre.WriteString(models.rendered[name])
	}
	b.WriteString(pre.String())
	b.WriteString(body.String())

	b.WriteString("def new_plugin(**kwargs: Any) -> Plugin:\n")
	b.WriteString("    \"\"\"Build a plugin instance from this contract. Same as Plugin(CONTRACT, **kwargs).\"\"\"\n")
	b.WriteString("    return Plugin(CONTRACT, **kwargs)\n")
	return b.String(), nil
}

// optionalFields copies the fields with the required markers stripped, for the credential model only
// (the reasoning is at the call site).
func optionalFields(fs []Field) []Field {
	out := make([]Field, len(fs))
	copy(out, fs)
	for i := range out {
		out[i].Required = false
	}
	return out
}

func opComment(op OperationDecl, side string) string {
	label := orDefaultStr(op.Label, op.ID)
	if op.Desc != "" {
		return fmt.Sprintf("%s of %q.\n\n%s", side, label, op.Desc)
	}
	return fmt.Sprintf("%s of %q.", side, label)
}

// pyRegisterFn is one operation's registration function. Its signature is fully concrete — type safety
// lives in this layer, and the runtime library holds no generics and needs none.
func pyRegisterFn(op OperationDecl, name string) string {
	var b strings.Builder
	fn := "on_" + op.ID
	if op.Stream {
		fmt.Fprintf(&b, "%sHandler = Callable[[Ctx, %sIn, Emitter], Awaitable[None]]\n\n\n", name, name)
		fmt.Fprintf(&b, "def %s(p: Plugin, fn: %sHandler) -> None:\n", fn, name)
		fmt.Fprintf(&b, "    \"\"\"Register the implementation of %q (streaming: emit frames with out.text/out.json/out.vars).\"\"\"\n", orDefaultStr(op.Label, op.ID))
		b.WriteString("\n    async def _invoke(ctx: Ctx, raw: Dict[str, Any], out: Emitter) -> None:\n")
		fmt.Fprintf(&b, "        await fn(ctx, %sIn.model_validate(raw), out)\n\n", name)
		fmt.Fprintf(&b, "    p.register(%s, _invoke)\n\n\n", jsonQuote(op.ID))
		return b.String()
	}
	fmt.Fprintf(&b, "%sHandler = Callable[[Ctx, %sIn], Union[%sOut, Awaitable[Optional[%sOut]], None]]\n\n\n", name, name, name, name)
	fmt.Fprintf(&b, "def %s(p: Plugin, fn: %sHandler) -> None:\n", fn, name)
	fmt.Fprintf(&b, "    \"\"\"Register the implementation of %q. The handler may be an async def or a plain function.\"\"\"\n", orDefaultStr(op.Label, op.ID))
	b.WriteString("\n    async def _invoke(ctx: Ctx, raw: Dict[str, Any], out: Emitter) -> None:\n")
	fmt.Fprintf(&b, "        res = fn(ctx, %sIn.model_validate(raw))\n", name)
	b.WriteString("        if inspect.isawaitable(res):\n            res = await res\n")
	// Returning None is a legitimate implementation: a side-effect-only operation should not have to
	// invent an empty output object.
	b.WriteString("        if res is not None:\n            out.vars(res)\n\n")
	fmt.Fprintf(&b, "    p.register(%s, _invoke)\n\n\n", jsonQuote(op.ID))
	return b.String()
}

// pyModel renders one pydantic model, along with the nested models it depends on, which are emitted
// first.
func pyModel(name, doc string, fields []Field, models *modelSet, owner string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "class %s(BaseModel):\n", name)
	if doc != "" {
		fmt.Fprintf(&b, "    \"\"\"%s\"\"\"\n\n", indentDoc(doc, "    "))
	}
	if len(fields) == 0 {
		b.WriteString("    pass\n\n\n")
		return b.String()
	}
	for _, f := range fields {
		// The comment goes **above** the field: people read downwards, and a trailing comment means looking
		// back
		if c := strings.TrimSpace(f.Label + " " + f.Desc); c != "" {
			b.WriteString(docComment("    # ", c))
		}
		typ := pyFieldType(f, owner, models)
		line := "    " + pyFieldName(f.Name) + ": " + typ
		if def := pyFieldDefault(f, typ); def != "" {
			line += " = " + def
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n\n")
	return b.String()
}

// pyFieldName uses the contract name as the field name (it is snake_case already), adding a trailing
// underscore on a keyword collision. What goes over the wire is still the contract name, held together
// by an alias (see model_config).
func pyFieldName(name string) string {
	if pyKeywords[name] {
		return name + "_"
	}
	return name
}

var pyKeywords = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true, "assert": true,
	"async": true, "await": true, "break": true, "class": true, "continue": true, "def": true,
	"del": true, "elif": true, "else": true, "except": true, "finally": true, "for": true,
	"from": true, "global": true, "if": true, "import": true, "in": true, "is": true,
	"lambda": true, "nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
}

// pyFieldType turns a contract field into a Python type annotation.
func pyFieldType(f Field, owner string, models *modelSet) string {
	base := pyBaseType(f, owner, models)
	if !f.Required && needsOptional(f) {
		return "Optional[" + base + "]"
	}
	return base
}

// needsOptional wraps in Optional only when a type has no natural zero value and the field is not
// required.
//
// Strings, numbers, bools, arrays and dicts all have a zero value, and wrapping them would only sprinkle
// None checks through the implementation; structs (json with fields) and files do not — an empty shell
// model is not the same as absent.
func needsOptional(f Field) bool {
	if f.Type == "file" || len(f.OneOf) > 0 {
		return true
	}
	return f.Type == "json" && len(f.Fields) > 0
}

func pyBaseType(f Field, owner string, models *modelSet) string {
	if len(f.Types) > 1 {
		return "Any" // a scalar union (number|string): Python has no more honest expression than Any
	}
	switch f.Type {
	case "number":
		if isIntGoType(f.GoType) {
			return "int"
		}
		return "float"
	case "boolean":
		return "bool"
	case "file":
		return "File"
	case "enum":
		if len(f.Options) > 0 {
			opts := make([]string, 0, len(f.Options))
			for _, o := range f.Options {
				opts = append(opts, jsonQuote(o.Value))
			}
			return "Literal[" + strings.Join(opts, ", ") + "]"
		}
		return "str"
	case "json":
		if len(f.OneOf) > 0 {
			return pyUnionType(f, owner, models)
		}
		if f.Opaque {
			return "Dict[str, Any]"
		}
		if f.ValueType != nil {
			return "Dict[str, " + pyBaseType(*f.ValueType, owner, models) + "]"
		}
		if len(f.Fields) > 0 {
			return pyEnsureModel(modelNameOf(f, owner), f.Fields, models)
		}
		return "Dict[str, Any]"
	case "array":
		if len(f.OneOf) > 0 {
			return "List[" + pyUnionType(f, owner, models) + "]"
		}
		if f.ItemType == "file" {
			return "List[File]"
		}
		if f.Opaque {
			return "List[Any]"
		}
		if len(f.Fields) > 0 {
			return "List[" + pyEnsureModel(modelNameOf(f, owner), f.Fields, models) + "]"
		}
		switch f.ItemType {
		case "number":
			if isIntGoType(f.GoType) {
				return "List[int]"
			}
			return "List[float]"
		case "boolean":
			return "List[bool]"
		case "string":
			return "List[str]"
		}
		return "List[Any]"
	}
	return "str" // string, text and secret are all strings
}

// pyUnionType renders a structural union. The runtime value simply is the branch's own shape, with no
// discriminator, and pydantic's smart union picks by shape — when it cannot decide, the handler gets
// whichever is closest, so keeping the branches distinguishable is the declarer's responsibility.
func pyUnionType(f Field, owner string, models *modelSet) string {
	parts := make([]string, 0, len(f.OneOf))
	for _, v := range f.OneOf {
		name := variantModelName(v)
		switch {
		case len(v.Fields) > 0 && v.Type == "array":
			parts = append(parts, "List["+pyEnsureModel(name, v.Fields, models)+"]")
		case len(v.Fields) > 0:
			parts = append(parts, pyEnsureModel(name, v.Fields, models))
		case v.Type == "array":
			parts = append(parts, "List[Any]")
		default:
			parts = append(parts, pyScalarType(v.Type))
		}
	}
	return "Union[" + strings.Join(parts, ", ") + "]"
}

func pyScalarType(t string) string {
	switch t {
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "json":
		return "Dict[str, Any]"
	}
	return "str"
}

func pyEnsureModel(name string, fields []Field, models *modelSet) string {
	models.ensure(name, fields, func() {
		models.setRendered(name, pyModel(name, "", fields, models, name))
	})
	return name
}

// modelNameOf gives a field's struct name: goType when it supplies one (so a struct referenced in
// several places is defined once), otherwise a stable name built from the owning type plus the field
// name.
func modelNameOf(f Field, owner string) string {
	if f.GoType != "" && !isIntGoType(f.GoType) {
		return f.GoType
	}
	return anonModelName(owner, f.Name)
}

// pyFieldDefault is an optional field's default. Required fields get none, which is precisely how
// "required" is expressed in pydantic.
func pyFieldDefault(f Field, typ string) string {
	if f.Required {
		return ""
	}
	if f.Default != nil {
		return renderPyLiteral(f.Default, 1)
	}
	if strings.HasPrefix(typ, "Optional[") {
		return "None"
	}
	switch {
	case strings.HasPrefix(typ, "List["):
		return "[]"
	case strings.HasPrefix(typ, "Dict["):
		return "{}"
	case typ == "int":
		return "0"
	case typ == "float":
		return "0.0"
	case typ == "bool":
		return "False"
	case typ == "Any":
		return "None"
	case strings.HasPrefix(typ, "Literal["):
		return "" // an enum has no natural zero value: give no default and let the declarer write one or mark it required
	}
	return jsonQuote("")
}

// indentDoc indents a multi-line description and strips trailing whitespace (indenting a blank line
// would leave a line of invisible spaces).
func indentDoc(doc, pad string) string {
	lines := strings.Split(doc, "\n")
	for i, l := range lines {
		if i == 0 {
			continue
		}
		lines[i] = strings.TrimRight(pad+l, " \t")
	}
	return strings.Join(lines, "\n")
}

func pyExports(m *Manifest, models *modelSet) []string {
	out := []string{"CONTRACT", "new_plugin"}
	if m.Credential != nil && len(m.Credential.Fields) > 0 {
		out = append(out, "Credential", "credential")
	}
	for _, op := range m.Operations {
		n := exportName(op.ID)
		out = append(out, n+"In", n+"Out", "on_"+op.ID)
	}
	for _, e := range m.Events {
		out = append(out, exportName(e.ID)+"Event", "trigger_"+e.ID)
	}
	out = append(out, models.order...)
	sort.Strings(out)
	return out
}
