package sokelgen

// 从 sokel.yaml 渲染 Python 插件的类型化外壳（pydantic 模型 + 注册口 + 触发口）。
//
// 为什么 Python 也走代码生成（而不是运行时读 YAML 产出契约）：契约是**声明**，
// 而声明的价值在于「写错当场知道」。运行时读 YAML 的话，字段拼错要等平台调过来才炸，
// 而且实现里拿到的仍是裸 dict —— 那正是这套 SDK 要杜绝的东西。
// 生成一遍之后，in_.project 拼错是 IDE 里的红线，不是线上的一次失败调用。

import (
	"fmt"
	"sort"
	"strings"
)

// modelSet：渲染过程中收集到的具名结构，按**先依赖后引用**的顺序排列。
type modelSet struct {
	order    []string
	fields   map[string][]Field
	rendered map[string]string
}

func newModelSet() *modelSet {
	return &modelSet{fields: map[string][]Field{}, rendered: map[string]string{}}
}

func (s *modelSet) setRendered(name, src string) { s.rendered[name] = src }

// ensure 登记一个具名结构；已存在则原样返回名字（同一个结构只定义一次）。
// render 先跑、再 append：于是子结构总排在父结构前面，Python 里不必依赖前向引用。
func (s *modelSet) ensure(name string, fields []Field, render func()) string {
	if _, ok := s.fields[name]; ok {
		return name
	}
	s.fields[name] = fields
	render()
	s.order = append(s.order, name)
	return name
}

// RenderPythonPlugin 生成 Python 侧的全部类型化外壳。
func RenderPythonPlugin(m *Manifest, doc string) (string, error) {
	cj, err := contractJSON(m, doc)
	if err != nil {
		return "", err
	}
	models := newModelSet()
	var body strings.Builder

	// 凭证：一个模型 + 一个读取函数。裸 ctx.credential["api_key"] 拼错是静默绑空，
	// 这就是凭证字段最典型的失效方式（尤其事件源，游标/会话全在凭证里）。
	if m.Credential != nil && len(m.Credential.Fields) > 0 {
		// 凭证模型的字段**一律带默认值**，哪怕契约里标了 required。
		// required 说的是「用户在界面上必须填」，不是「每次调用一定有」——
		// 凭证刚建、还没登录、事件源实例没绑凭证时，平台下发的就是个空表。
		// 按 required 生成的话，`Credential(**ctx.credential)` 会直接抛校验错，
		// 而那是插件里最不该炸的地方（实测：事件源第一次启动就栽在这儿）。
		body.WriteString(pyModel("Credential", "凭证字段（平台随每次调用下发，插件从不落地）。\n\n字段都可缺省：required 是「界面上必须填」，不是「每次调用一定有」。",
			optionalFields(m.Credential.Fields), models, "Credential"))
		body.WriteString("def credential(ctx: Any) -> Credential:\n")
		body.WriteString("    \"\"\"把本次调用的凭证读成类型化对象（操作 ctx 与事件源 ctx 都收）。\"\"\"\n")
		body.WriteString("    return ctx.credential_as(Credential)\n\n\n")
	}

	ops := append([]OperationDecl(nil), m.Operations...)
	sort.Slice(ops, func(i, j int) bool { return ops[i].ID < ops[j].ID })
	for _, op := range ops {
		name := exportName(op.ID)
		body.WriteString(pyModel(name+"In", opComment(op, "入参"), op.Inputs, models, name+"In"))
		body.WriteString(pyModel(name+"Out", opComment(op, "出参"), op.Outputs, models, name+"Out"))
		body.WriteString(pyRegisterFn(op, name))
	}

	events := append([]EventDecl(nil), m.Events...)
	sort.Slice(events, func(i, j int) bool { return events[i].ID < events[j].ID })
	for _, e := range events {
		name := exportName(e.ID) + "Event"
		body.WriteString(pyModel(name, orDefaultStr(e.Label, e.ID)+" 事件的 payload", e.Fields, models, name))
		fn := "trigger_" + e.ID
		fmt.Fprintf(&body, "async def %s(ctx: SourceCtx, event_id: str, payload: %s) -> None:\n", fn, name)
		fmt.Fprintf(&body, "    \"\"\"推一条「%s」事件。event_id 是幂等键：同一条外部消息重复推只触发一次。\"\"\"\n", orDefaultStr(e.Label, e.ID))
		fmt.Fprintf(&body, "    await ctx.trigger(%s, event_id, payload)\n\n\n", jsonQuote(e.ID))
	}

	var b strings.Builder
	b.WriteString("# Code generated by sokel-gen. DO NOT EDIT.\n#\n")
	b.WriteString("# 契约声明在 sokel.yaml —— 改字段请改那份，然后重新跑 `sokel-gen generate`。\n")
	b.WriteString("# 直接改本文件的话，下次生成就没了。\n\n")
	b.WriteString("from __future__ import annotations\n\n")
	b.WriteString("from typing import Any, Awaitable, Callable, Dict, List, Literal, Optional, Union\n\n")
	b.WriteString("import inspect\n\n")
	b.WriteString("from pydantic import BaseModel\n")
	b.WriteString("from sokel import Ctx, Emitter, File, Plugin, SourceCtx\n\n")
	b.WriteString("__all__ = [\n")
	for _, n := range pyExports(m, models) {
		b.WriteString("    " + jsonQuote(n) + ",\n")
	}
	b.WriteString("]\n\n")
	b.WriteString("# 上报给平台的契约（与 sokel.yaml 等价；三种语言的生成物里是同一份）。\n")
	b.WriteString("CONTRACT: Dict[str, Any] = " + renderPyLiteral(cj, 0) + "\n\n\n")

	// 具名结构先于引用它的模型输出
	var pre strings.Builder
	for _, name := range models.order {
		pre.WriteString(models.rendered[name])
	}
	b.WriteString(pre.String())
	b.WriteString(body.String())

	b.WriteString("def new_plugin(**kwargs: Any) -> Plugin:\n")
	b.WriteString("    \"\"\"按本契约建插件实例。等价于 Plugin(CONTRACT, **kwargs)。\"\"\"\n")
	b.WriteString("    return Plugin(CONTRACT, **kwargs)\n")
	return b.String(), nil
}

// optionalFields：复制一份字段并去掉 required 标记（凭证模型专用，见调用点的理由）。
func optionalFields(fs []Field) []Field {
	out := make([]Field, len(fs))
	copy(out, fs)
	for i := range out {
		out[i].Required = false
	}
	return out
}

func opComment(op OperationDecl, side string) string {
	label := orDefaultStr(op.Label, op.ID)
	if op.Desc != "" {
		return fmt.Sprintf("%s 的%s。\n\n%s", label, side, op.Desc)
	}
	return fmt.Sprintf("%s 的%s。", label, side)
}

// pyRegisterFn 一个操作的注册口。签名完全具体——类型安全就落在这一层，
// 运行时库里没有任何泛型，也不必有。
func pyRegisterFn(op OperationDecl, name string) string {
	var b strings.Builder
	fn := "on_" + op.ID
	if op.Stream {
		fmt.Fprintf(&b, "%sHandler = Callable[[Ctx, %sIn, Emitter], Awaitable[None]]\n\n\n", name, name)
		fmt.Fprintf(&b, "def %s(p: Plugin, fn: %sHandler) -> None:\n", fn, name)
		fmt.Fprintf(&b, "    \"\"\"注册「%s」的实现（流式：用 out.text/out.json/out.vars 逐帧产出）。\"\"\"\n", orDefaultStr(op.Label, op.ID))
		b.WriteString("\n    async def _invoke(ctx: Ctx, raw: Dict[str, Any], out: Emitter) -> None:\n")
		fmt.Fprintf(&b, "        await fn(ctx, %sIn.model_validate(raw), out)\n\n", name)
		fmt.Fprintf(&b, "    p.register(%s, _invoke)\n\n\n", jsonQuote(op.ID))
		return b.String()
	}
	fmt.Fprintf(&b, "%sHandler = Callable[[Ctx, %sIn], Union[%sOut, Awaitable[Optional[%sOut]], None]]\n\n\n", name, name, name, name)
	fmt.Fprintf(&b, "def %s(p: Plugin, fn: %sHandler) -> None:\n", fn, name)
	fmt.Fprintf(&b, "    \"\"\"注册「%s」的实现。handler 可以是 async def，也可以是普通函数。\"\"\"\n", orDefaultStr(op.Label, op.ID))
	b.WriteString("\n    async def _invoke(ctx: Ctx, raw: Dict[str, Any], out: Emitter) -> None:\n")
	fmt.Fprintf(&b, "        res = fn(ctx, %sIn.model_validate(raw))\n", name)
	b.WriteString("        if inspect.isawaitable(res):\n            res = await res\n")
	// 返回 None 也是合法实现：只做副作用的操作不必硬造一个空壳出参
	b.WriteString("        if res is not None:\n            out.vars(res)\n\n")
	fmt.Fprintf(&b, "    p.register(%s, _invoke)\n\n\n", jsonQuote(op.ID))
	return b.String()
}

// pyModel 渲染一个 pydantic 模型（连同它依赖的嵌套模型，后者先输出）。
func pyModel(name, doc string, fields []Field, models *modelSet, owner string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "class %s(BaseModel):\n", name)
	if doc != "" {
		fmt.Fprintf(&b, "    \"\"\"%s\"\"\"\n\n", indentDoc(doc, "    "))
	}
	if len(fields) == 0 {
		b.WriteString("    pass\n\n\n")
		return b.String()
	}
	for _, f := range fields {
		// 注释在字段**上方**：读的人是从上往下读的，注释跟在后面等于要回头看
		if c := strings.TrimSpace(f.Label + " " + f.Desc); c != "" {
			b.WriteString(docComment("    # ", c))
		}
		typ := pyFieldType(f, owner, models)
		line := "    " + pyFieldName(f.Name) + ": " + typ
		if def := pyFieldDefault(f, typ); def != "" {
			line += " = " + def
		}
		b.WriteString(line + "\n")
	}
	b.WriteString("\n\n")
	return b.String()
}

// pyFieldName：契约名直接当字段名（契约名本就是 snake_case）。撞上关键字加下划线后缀——
// 与平台交换的仍是契约名，靠 alias 兜住（见 model_config）。
func pyFieldName(name string) string {
	if pyKeywords[name] {
		return name + "_"
	}
	return name
}

var pyKeywords = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true, "assert": true,
	"async": true, "await": true, "break": true, "class": true, "continue": true, "def": true,
	"del": true, "elif": true, "else": true, "except": true, "finally": true, "for": true,
	"from": true, "global": true, "if": true, "import": true, "in": true, "is": true,
	"lambda": true, "nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
}

// pyFieldType 契约字段 → Python 类型标注。
func pyFieldType(f Field, owner string, models *modelSet) string {
	base := pyBaseType(f, owner, models)
	if !f.Required && needsOptional(f) {
		return "Optional[" + base + "]"
	}
	return base
}

// needsOptional：没有天然零值的类型在非必填时才包 Optional。
//
// 字符串/数字/布尔/数组/字典各有零值，包一层只会让实现里到处判 None；
// 而结构（有 fields 的 json）与文件没有——一个空壳模型不是「没有」。
func needsOptional(f Field) bool {
	if f.Type == "file" || len(f.OneOf) > 0 {
		return true
	}
	return f.Type == "json" && len(f.Fields) > 0
}

func pyBaseType(f Field, owner string, models *modelSet) string {
	if len(f.Types) > 1 {
		return "Any" // 标量联合（number|string）：Python 侧没有比 Any 更诚实的表达
	}
	switch f.Type {
	case "number":
		if isIntGoType(f.GoType) {
			return "int"
		}
		return "float"
	case "boolean":
		return "bool"
	case "file":
		return "File"
	case "enum":
		if len(f.Options) > 0 {
			opts := make([]string, 0, len(f.Options))
			for _, o := range f.Options {
				opts = append(opts, jsonQuote(o.Value))
			}
			return "Literal[" + strings.Join(opts, ", ") + "]"
		}
		return "str"
	case "json":
		if len(f.OneOf) > 0 {
			return pyUnionType(f, owner, models)
		}
		if f.Opaque {
			return "Dict[str, Any]"
		}
		if f.ValueType != nil {
			return "Dict[str, " + pyBaseType(*f.ValueType, owner, models) + "]"
		}
		if len(f.Fields) > 0 {
			return pyEnsureModel(modelNameOf(f, owner), f.Fields, models)
		}
		return "Dict[str, Any]"
	case "array":
		if len(f.OneOf) > 0 {
			return "List[" + pyUnionType(f, owner, models) + "]"
		}
		if f.ItemType == "file" {
			return "List[File]"
		}
		if f.Opaque {
			return "List[Any]"
		}
		if len(f.Fields) > 0 {
			return "List[" + pyEnsureModel(modelNameOf(f, owner), f.Fields, models) + "]"
		}
		switch f.ItemType {
		case "number":
			if isIntGoType(f.GoType) {
				return "List[int]"
			}
			return "List[float]"
		case "boolean":
			return "List[bool]"
		case "string":
			return "List[str]"
		}
		return "List[Any]"
	}
	return "str" // string / text / secret 都是字符串
}

// pyUnionType：结构联合。运行值就是分支本身的形状（不带 discriminator），
// pydantic 的 smart union 按形状挑——挑不中时 handler 拿到的是最像的那个，
// 所以分支之间形状要有区分度，这是声明者的责任。
func pyUnionType(f Field, owner string, models *modelSet) string {
	parts := make([]string, 0, len(f.OneOf))
	for _, v := range f.OneOf {
		name := variantModelName(v)
		switch {
		case len(v.Fields) > 0 && v.Type == "array":
			parts = append(parts, "List["+pyEnsureModel(name, v.Fields, models)+"]")
		case len(v.Fields) > 0:
			parts = append(parts, pyEnsureModel(name, v.Fields, models))
		case v.Type == "array":
			parts = append(parts, "List[Any]")
		default:
			parts = append(parts, pyScalarType(v.Type))
		}
	}
	return "Union[" + strings.Join(parts, ", ") + "]"
}

func pyScalarType(t string) string {
	switch t {
	case "number":
		return "float"
	case "boolean":
		return "bool"
	case "json":
		return "Dict[str, Any]"
	}
	return "str"
}

func pyEnsureModel(name string, fields []Field, models *modelSet) string {
	models.ensure(name, fields, func() {
		models.setRendered(name, pyModel(name, "", fields, models, name))
	})
	return name
}

// modelNameOf：字段的结构名。goType 给了就用它（同一结构多处引用只定义一次），
// 否则按「所属类型 + 字段名」造一个稳定的名字。
func modelNameOf(f Field, owner string) string {
	if f.GoType != "" && !isIntGoType(f.GoType) {
		return f.GoType
	}
	return anonModelName(owner, f.Name)
}

// pyFieldDefault 非必填字段的默认值。必填字段不给默认——那正是「必填」在 pydantic 里的表达。
func pyFieldDefault(f Field, typ string) string {
	if f.Required {
		return ""
	}
	if f.Default != nil {
		return renderPyLiteral(f.Default, 1)
	}
	if strings.HasPrefix(typ, "Optional[") {
		return "None"
	}
	switch {
	case strings.HasPrefix(typ, "List["):
		return "[]"
	case strings.HasPrefix(typ, "Dict["):
		return "{}"
	case typ == "int":
		return "0"
	case typ == "float":
		return "0.0"
	case typ == "bool":
		return "False"
	case typ == "Any":
		return "None"
	case strings.HasPrefix(typ, "Literal["):
		return "" // enum 没有天然零值：不给默认，让声明者显式写 default 或标 required
	}
	return jsonQuote("")
}

// indentDoc 给多行说明加缩进，并去掉尾随空白（空行加缩进就成了一行看不见的空格）。
func indentDoc(doc, pad string) string {
	lines := strings.Split(doc, "\n")
	for i, l := range lines {
		if i == 0 {
			continue
		}
		lines[i] = strings.TrimRight(pad+l, " \t")
	}
	return strings.Join(lines, "\n")
}

func pyExports(m *Manifest, models *modelSet) []string {
	out := []string{"CONTRACT", "new_plugin"}
	if m.Credential != nil && len(m.Credential.Fields) > 0 {
		out = append(out, "Credential", "credential")
	}
	for _, op := range m.Operations {
		n := exportName(op.ID)
		out = append(out, n+"In", n+"Out", "on_"+op.ID)
	}
	for _, e := range m.Events {
		out = append(out, exportName(e.ID)+"Event", "trigger_"+e.ID)
	}
	out = append(out, models.order...)
	sort.Strings(out)
	return out
}
