// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// generatedFileName：生成物的固定文件名。解析包时要跳过它——否则上一轮的生成结果
// 会被当成源码再解析一遍。
const generatedFileName = "zz_sokel.go"

// SchemaRef：schema 包的引用方式。Import 是完整导入路径，Name 是代码里的包名前缀——
// 二者不同（"a/b/schema" 与 "schema"），早先混用会生成出 import 路径当前缀的坏代码。
type SchemaRef struct {
	Import string
	Name   string
}

// OpIO：一个操作的入/出参契约，连同它的 Go 类型名——生成的注册代码用类型做 key，
// 运行时 Register 据此查表，插件作者的代码一行不用改（docs/plugin-sdk-multilang.md §1）。
type OpIO struct {
	OpID       string
	Label      string
	Desc       string
	SchemaType string // 声明该操作的 schema 类型名（生成的注册代码用 sokel.OperationOf(&schema.X{}) 取契约）
	InType     string
	OutType    string
	Stream     bool // 流式：handler 拿到类型化产出器，可多次发
	Inputs     []Field
	Outputs    []Field
}

// RenderContract 把契约渲染成一个 zz_sokel.go 源文件。
//
// 走 go/format 而不是自己对齐缩进：生成物是要提交进仓库、进 code review 的
// （契约变更看得见，这是 codegen 相对反射的主要收益之一），格式必须与手写代码一致。
func RenderContract(pkg string, ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("没有可生成的操作（未找到 sokel.Register 调用？）")
	}
	// 按 OpID 排序：生成物必须是确定性的，否则每次生成都产生无意义 diff。
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// The contract is derived from the source of the input/output structs (AST, not runtime\n")
	b.WriteString("// reflection). Change the struct and its tags, then regenerate; edits here are lost.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import \"github.com/sokel-dev/sokel-plugin-sdk/sokel\"\n\n")
	b.WriteString("func init() {\n")
	for _, op := range sorted {
		fmt.Fprintf(&b, "\tsokel.RegisterIO[%s, %s](%s, sokel.IO{\n", op.InType, op.OutType, strconv.Quote(op.OpID))
		b.WriteString("\t\tInputs: " + renderFields(op.Inputs, 2, "sokel") + ",\n")
		b.WriteString("\t\tOutputs: " + renderFields(op.Outputs, 2, "sokel") + ",\n")
		b.WriteString("\t})\n")
	}
	b.WriteString("}\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("生成的代码无法格式化（多半是渲染有 bug）: %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// renderFields：字段字面量。q 是包限定符——操作契约落在 sokel.RegisterIO 里（"sokel"），
// 凭证契约落在 []contract.Field 里（"contract"）。两个包的 Field 是同一个类型
// （sokel.Field = contract.Field 别名），但生成物只能 import 其中一个：
// plugin-core 里的声明不能 import go-sdk，那会成环。
func renderFields(fs []Field, indent int, q string) string {
	if len(fs) == 0 {
		return "nil"
	}
	pad := strings.Repeat("\t", indent)
	var b strings.Builder
	b.WriteString("[]" + q + ".Field{\n")
	for _, f := range fs {
		b.WriteString(pad + "\t" + renderField(f, indent+1, false, q) + ",\n")
	}
	b.WriteString(pad + "}")
	return b.String()
}

// renderField：withType=false 时省略 `sokel.Field` 前缀——在 []sokel.Field{} 里它是冗余的，
// 与 gofmt -s 的惯例一致，生成物短一截也更好读。
func renderField(f Field, indent int, withType bool, q string) string {
	pad := strings.Repeat("\t", indent)
	var parts []string
	add := func(s string) { parts = append(parts, pad+"\t"+s) }

	add("Name: " + strconv.Quote(f.Name))
	if f.Label != "" {
		add("Label: " + strconv.Quote(f.Label))
	}
	add("Type: " + typeExpr(f.Type, q))
	if len(f.Types) > 0 {
		var ts []string
		for _, t := range f.Types {
			ts = append(ts, typeExpr(t, q))
		}
		add("Types: []" + q + ".ParamType{" + strings.Join(ts, ", ") + "}")
	}
	if f.Required {
		add("Required: true")
	}
	if f.Default != nil {
		add("Default: " + renderLiteral(f.Default))
	}
	if f.Desc != "" {
		add("Desc: " + strconv.Quote(f.Desc))
	}
	if len(f.Options) > 0 {
		var os []string
		for _, o := range f.Options {
			s := "{Value: " + strconv.Quote(o.Value)
			if o.Label != "" {
				s += ", Label: " + strconv.Quote(o.Label)
			}
			os = append(os, s+"}")
		}
		add("Options: []" + q + ".Option{" + strings.Join(os, ", ") + "}")
	}
	if len(f.Fields) > 0 {
		add("Fields: " + renderFields(f.Fields, indent+1, q))
	}
	if f.ValueType != nil {
		add("ValueType: &" + q + ".Field" + renderField(*f.ValueType, indent+1, false, q))
	}
	if f.Opaque {
		add("Opaque: true")
	}
	if len(f.OneOf) > 0 {
		var vs []string
		for _, v := range f.OneOf {
			s := "{Name: " + strconv.Quote(v.Name)
			if v.Label != "" {
				s += ", Label: " + strconv.Quote(v.Label)
			}
			s += ", Type: " + typeExpr(v.Type, q)
			if len(v.Fields) > 0 {
				s += ", Fields: " + renderFields(v.Fields, indent+2, q)
			}
			vs = append(vs, s+"}")
		}
		add("OneOf: []" + q + ".OneOfVariant{" + strings.Join(vs, ", ") + "}")
	}
	head := "{"
	if withType {
		head = q + ".Field{"
	}
	return head + "\n" + strings.Join(parts, ",\n") + ",\n" + pad + "}"
}

// renderLiteral：default 值的字面量。契约里的 default 只可能是 string/number/bool
// （从 tag 解析而来），其余形态一律退回字符串，不猜。
func renderLiteral(v any) string {
	switch t := v.(type) {
	case string:
		return strconv.Quote(t)
	case bool:
		return strconv.FormatBool(t)
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	case int:
		return strconv.Itoa(t)
	}
	return strconv.Quote(fmt.Sprint(v))
}

// typeExpr：契约类型 → 可读的常量表达式。生成物要进 code review，
// sokel.TString 比 sokel.ParamType("string") 一眼就能扫过去。未知类型不硬凑常量。
func typeExpr(t, q string) string {
	switch t {
	case "string":
		return q + ".TString"
	case "number":
		return q + ".TNumber"
	case "boolean":
		return q + ".TBool"
	case "file":
		return q + ".TFile"
	case "json":
		return q + ".TJSON"
	case "array":
		return q + ".TArray"
	case "enum":
		return q + ".TEnum"
	}
	return q + ".ParamType(" + strconv.Quote(t) + ")"
}
