// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

// Renders the typed shell of a TypeScript plugin from manifest.yml: interfaces, registration functions
// and triggers.
//
// This is not RenderTS (the execution-contract table exported for the frontend to check its UI schema
// against): that one is **for the platform frontend**, this one is **for the plugin author** — two
// consumers of the same IR, and they should not be merged into one.
//
// Why not zod: a zod schema is a runtime object, so declaring a contract with it means the contract is
// knowable only once the code runs — and every other language would have to reimplement that DSL. The
// declaration stays in manifest.yml, language-neutral, and TS takes only the types, which is exactly
// where TS is strongest: compile-time types with zero runtime cost.

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// RenderTSPlugin generates the whole typed shell on the TS side.
func RenderTSPlugin(m *Manifest, doc string) (string, error) {
	cj, err := contractJSON(m, doc)
	if err != nil {
		return "", err
	}
	models := newModelSet()
	var body strings.Builder

	if m.Credential != nil && len(m.Credential.Fields) > 0 {
		body.WriteString(tsInterface("Credential", "Credential fields (the platform injects them with every call; a plugin never stores them).", m.Credential.Fields, models, "Credential"))
	}

	ops := append([]OperationDecl(nil), m.Operations...)
	sort.Slice(ops, func(i, j int) bool { return ops[i].ID < ops[j].ID })
	for _, op := range ops {
		name := exportName(op.ID)
		body.WriteString(tsInterface(name+"In", opComment(op, "Inputs"), op.Inputs, models, name+"In"))
		body.WriteString(tsInterface(name+"Out", opComment(op, "Outputs"), op.Outputs, models, name+"Out"))
		body.WriteString(tsRegisterFn(op, name))
	}

	events := append([]EventDecl(nil), m.Events...)
	sort.Slice(events, func(i, j int) bool { return events[i].ID < events[j].ID })
	for _, e := range events {
		name := exportName(e.ID) + "Event"
		body.WriteString(tsInterface(name, "Payload of the "+strconv.Quote(orDefaultStr(e.Label, e.ID))+" event.", e.Fields, models, name))
		fn := "trigger" + exportName(e.ID)
		fmt.Fprintf(&body, "/** Push one %q event. eventId is the idempotency key: re-pushing the same upstream message triggers once. */\n", orDefaultStr(e.Label, e.ID))
		fmt.Fprintf(&body, "export function %s(ctx: SourceCtx, eventId: string, payload: %s): Promise<void> {\n", fn, name)
		fmt.Fprintf(&body, "  return ctx.trigger(%s, eventId, payload);\n}\n\n", jsonQuote(e.ID))
	}

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n//\n")
	b.WriteString("// The contract is declared in manifest.yml — change a field there and re-run `sokel-gen generate`.\n")
	b.WriteString("// Edits to this file are lost on the next generation.\n\n")
	b.WriteString("import { Plugin } from \"@sokel-dev/plugin-sdk\";\n")
	b.WriteString("import type { Config, ContractData, Ctx, Emitter, SokelFile, SourceCtx } from \"@sokel-dev/plugin-sdk\";\n\n")
	b.WriteString("/** The contract reported to the platform (equivalent to manifest.yml; all three languages embed this same JSON). */\n")
	b.WriteString("export const CONTRACT: ContractData = " + renderJSONLiteral(cj, 0) + ";\n\n")
	for _, name := range models.order {
		b.WriteString(models.rendered[name])
	}
	b.WriteString(body.String())
	b.WriteString("/** Build a plugin instance from this contract. */\n")
	b.WriteString("export function newPlugin(cfg: Omit<Config, \"contract\"> = {}): Plugin {\n")
	b.WriteString("  return new Plugin({ contract: CONTRACT, ...cfg });\n}\n")
	return b.String(), nil
}

func tsRegisterFn(op OperationDecl, name string) string {
	var b strings.Builder
	fn := "on" + name
	if op.Stream {
		fmt.Fprintf(&b, "export type %sHandler = (ctx: Ctx, input: %sIn, out: Emitter<%sOut>) => Promise<void> | void;\n\n", name, name, name)
		fmt.Fprintf(&b, "/** Register the implementation of %q (streaming: emit frames with out.text/out.json/out.vars). */\n", orDefaultStr(op.Label, op.ID))
		fmt.Fprintf(&b, "export function %s(p: Plugin, fn: %sHandler): void {\n", fn, name)
		fmt.Fprintf(&b, "  p.register(%s, async (ctx, raw, out) => {\n", jsonQuote(op.ID))
		fmt.Fprintf(&b, "    await fn(ctx, raw as unknown as %sIn, out as Emitter<%sOut>);\n  });\n}\n\n", name, name)
		return b.String()
	}
	fmt.Fprintf(&b, "export type %sHandler = (ctx: Ctx, input: %sIn) => %sOut | void | Promise<%sOut | void>;\n\n", name, name, name, name)
	fmt.Fprintf(&b, "/** Register the implementation of %q. */\n", orDefaultStr(op.Label, op.ID))
	fmt.Fprintf(&b, "export function %s(p: Plugin, fn: %sHandler): void {\n", fn, name)
	fmt.Fprintf(&b, "  p.register(%s, async (ctx, raw, out) => {\n", jsonQuote(op.ID))
	fmt.Fprintf(&b, "    const res = await fn(ctx, raw as unknown as %sIn);\n", name)
	// Returning void is a legitimate implementation: a side-effect-only operation should not have to
	// invent an empty output object.
	b.WriteString("    if (res) out.vars(res);\n  });\n}\n\n")
	return b.String()
}

// tsInterface renders one interface, along with the nested interfaces it depends on.
func tsInterface(name, doc string, fields []Field, models *modelSet, owner string) string {
	var b strings.Builder
	if doc != "" {
		b.WriteString("/**\n" + docComment(" * ", doc) + " */\n")
	}
	fmt.Fprintf(&b, "export interface %s {\n", name)
	for _, f := range fields {
		if c := strings.TrimSpace(f.Label + " " + f.Desc); c != "" {
			b.WriteString("  /** " + strings.ReplaceAll(c, "*/", "*\\/") + " */\n")
		}
		opt := "?"
		if f.Required {
			opt = ""
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", tsFieldName(f.Name), opt, tsType(f, owner, models))
	}
	if len(fields) == 0 {
		b.WriteString("  // this operation has no fields\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

// tsFieldName uses the contract name as the property name directly, quoting it when it is not a valid
// identifier: a property name must match the wire field name character for character, since renaming it
// makes it a different field.
func tsFieldName(name string) string {
	for i, r := range name {
		ok := r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return jsonQuote(name)
		}
	}
	return name
}

func tsType(f Field, owner string, models *modelSet) string {
	if len(f.Types) > 1 {
		return "unknown" // a scalar union: unknown forces the caller to narrow, which is more honest than any
	}
	switch f.Type {
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	case "file":
		return "SokelFile"
	case "enum":
		if len(f.Options) > 0 {
			opts := make([]string, 0, len(f.Options))
			for _, o := range f.Options {
				opts = append(opts, jsonQuote(o.Value))
			}
			return strings.Join(opts, " | ")
		}
		return "string"
	case "json":
		if len(f.OneOf) > 0 {
			return tsUnion(f, owner, models)
		}
		if f.Opaque {
			return "Record<string, unknown>"
		}
		if f.ValueType != nil {
			return "Record<string, " + tsType(*f.ValueType, owner, models) + ">"
		}
		if len(f.Fields) > 0 {
			return tsEnsure(modelNameOf(f, owner), f.Fields, models)
		}
		return "Record<string, unknown>"
	case "array":
		if len(f.OneOf) > 0 {
			return "Array<" + tsUnion(f, owner, models) + ">"
		}
		if f.ItemType == "file" {
			return "SokelFile[]"
		}
		if f.Opaque {
			return "unknown[]"
		}
		if len(f.Fields) > 0 {
			return tsEnsure(modelNameOf(f, owner), f.Fields, models) + "[]"
		}
		switch f.ItemType {
		case "number":
			return "number[]"
		case "boolean":
			return "boolean[]"
		case "string":
			return "string[]"
		}
		return "unknown[]"
	}
	return "string"
}

// tsUnion renders a structural union. TS's union type fits the protocol better than any other language
// here: the runtime value simply is the branch's own shape, and the handler narrows it by inspecting
// fields.
func tsUnion(f Field, owner string, models *modelSet) string {
	parts := make([]string, 0, len(f.OneOf))
	for _, v := range f.OneOf {
		name := variantModelName(v)
		switch {
		case len(v.Fields) > 0 && v.Type == "array":
			parts = append(parts, tsEnsure(name, v.Fields, models)+"[]")
		case len(v.Fields) > 0:
			parts = append(parts, tsEnsure(name, v.Fields, models))
		case v.Type == "array":
			parts = append(parts, "unknown[]")
		case v.Type == "number":
			parts = append(parts, "number")
		case v.Type == "boolean":
			parts = append(parts, "boolean")
		case v.Type == "json":
			parts = append(parts, "Record<string, unknown>")
		default:
			parts = append(parts, "string")
		}
	}
	return strings.Join(parts, " | ")
}

func tsEnsure(name string, fields []Field, models *modelSet) string {
	models.ensure(name, fields, func() {
		models.setRendered(name, tsInterface(name, "", fields, models, name))
	})
	return name
}
