// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// generatedFileName is the fixed name of the generated file. Parsing the package must skip it, or the
// previous round's output gets parsed as source all over again.
const generatedFileName = "zz_sokel.go"

// SchemaRef is how the schema package is referenced. Import is the full import path and Name is the
// prefix used in code — the two differ ("a/b/schema" vs "schema"), and confusing them once produced
// code that used the import path as the prefix.
type SchemaRef struct {
	Import string
	Name   string
}

// OpIO is one operation's input/output contract together with its Go type names. The generated
// registration code keys off the types, the runtime Register looks them up, and the plugin author's own
// code needs no change (docs/plugin-sdk-multilang.md §1).
type OpIO struct {
	OpID       string
	Label      string
	Desc       string
	SchemaType string // the schema type declaring this operation (the generated code reads the contract via sokel.OperationOf(&schema.X{}))
	InType     string
	OutType    string
	Stream     bool // streaming: the handler gets a typed emitter and may send many times
	Inputs     []Field
	Outputs    []Field
}

// RenderContract renders the contract into a single zz_sokel.go source file.
//
// It runs go/format rather than aligning indentation by hand: the output is committed and reviewed
// (contract changes being visible is one of codegen's main advantages over reflection), so its
// formatting has to match hand-written code.
func RenderContract(pkg string, ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("there are no operations to generate (no sokel.Register calls found?)")
	}
	// Sort by OpID: the output has to be deterministic, or every run produces a meaningless diff.
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// The contract is derived from the source of the input/output structs (AST, not runtime\n")
	b.WriteString("// reflection). Change the struct and its tags, then regenerate; edits here are lost.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import \"github.com/sokel-dev/sokel-plugin-sdk/sokel\"\n\n")
	b.WriteString("func init() {\n")
	for _, op := range sorted {
		fmt.Fprintf(&b, "\tsokel.RegisterIO[%s, %s](%s, sokel.IO{\n", op.InType, op.OutType, strconv.Quote(op.OpID))
		b.WriteString("\t\tInputs: " + renderFields(op.Inputs, 2, "sokel") + ",\n")
		b.WriteString("\t\tOutputs: " + renderFields(op.Outputs, 2, "sokel") + ",\n")
		b.WriteString("\t})\n")
	}
	b.WriteString("}\n")

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("the generated code will not format (most likely a rendering bug): %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// renderFields renders field literals. q is the package qualifier: an operation contract lands inside
// sokel.RegisterIO ("sokel") while a credential contract lands in []contract.Field ("contract"). Field
// is the same type in both packages (sokel.Field aliases contract.Field), but the output may import
// only one of them, because declarations inside plugin-core cannot import the SDK without a cycle.
func renderFields(fs []Field, indent int, q string) string {
	if len(fs) == 0 {
		return "nil"
	}
	pad := strings.Repeat("\t", indent)
	var b strings.Builder
	b.WriteString("[]" + q + ".Field{\n")
	for _, f := range fs {
		b.WriteString(pad + "\t" + renderField(f, indent+1, false, q) + ",\n")
	}
	b.WriteString(pad + "}")
	return b.String()
}

// renderField omits the `sokel.Field` prefix when withType is false: inside []sokel.Field{} it is
// redundant, which matches what gofmt -s does, and the shorter output reads better.
func renderField(f Field, indent int, withType bool, q string) string {
	pad := strings.Repeat("\t", indent)
	var parts []string
	add := func(s string) { parts = append(parts, pad+"\t"+s) }

	add("Name: " + strconv.Quote(f.Name))
	if f.Label != "" {
		add("Label: " + strconv.Quote(f.Label))
	}
	add("Type: " + typeExpr(f.Type, q))
	if len(f.Types) > 0 {
		var ts []string
		for _, t := range f.Types {
			ts = append(ts, typeExpr(t, q))
		}
		add("Types: []" + q + ".ParamType{" + strings.Join(ts, ", ") + "}")
	}
	if f.Required {
		add("Required: true")
	}
	if f.Default != nil {
		add("Default: " + renderLiteral(f.Default))
	}
	if f.Desc != "" {
		add("Desc: " + strconv.Quote(f.Desc))
	}
	if len(f.Options) > 0 {
		var os []string
		for _, o := range f.Options {
			s := "{Value: " + strconv.Quote(o.Value)
			if o.Label != "" {
				s += ", Label: " + strconv.Quote(o.Label)
			}
			os = append(os, s+"}")
		}
		add("Options: []" + q + ".Option{" + strings.Join(os, ", ") + "}")
	}
	if len(f.Fields) > 0 {
		add("Fields: " + renderFields(f.Fields, indent+1, q))
	}
	if f.ValueType != nil {
		add("ValueType: &" + q + ".Field" + renderField(*f.ValueType, indent+1, false, q))
	}
	if f.Opaque {
		add("Opaque: true")
	}
	if len(f.OneOf) > 0 {
		var vs []string
		for _, v := range f.OneOf {
			s := "{Name: " + strconv.Quote(v.Name)
			if v.Label != "" {
				s += ", Label: " + strconv.Quote(v.Label)
			}
			s += ", Type: " + typeExpr(v.Type, q)
			if len(v.Fields) > 0 {
				s += ", Fields: " + renderFields(v.Fields, indent+2, q)
			}
			vs = append(vs, s+"}")
		}
		add("OneOf: []" + q + ".OneOfVariant{" + strings.Join(vs, ", ") + "}")
	}
	head := "{"
	if withType {
		head = q + ".Field{"
	}
	return head + "\n" + strings.Join(parts, ",\n") + ",\n" + pad + "}"
}

// renderLiteral renders a default value. A contract default can only be a string, number or bool (it
// comes from a tag), and anything else falls back to a string rather than being guessed at.
func renderLiteral(v any) string {
	switch t := v.(type) {
	case string:
		return strconv.Quote(t)
	case bool:
		return strconv.FormatBool(t)
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	case int:
		return strconv.Itoa(t)
	}
	return strconv.Quote(fmt.Sprint(v))
}

// typeExpr turns a contract type into a readable constant expression. The output gets reviewed, and
// sokel.TString scans far faster than sokel.ParamType("string"). Unknown types are not forced into a
// constant.
func typeExpr(t, q string) string {
	switch t {
	case "string":
		return q + ".TString"
	case "number":
		return q + ".TNumber"
	case "boolean":
		return q + ".TBool"
	case "file":
		return q + ".TFile"
	case "json":
		return q + ".TJSON"
	case "array":
		return q + ".TArray"
	case "enum":
		return q + ".TEnum"
	}
	return q + ".ParamType(" + strconv.Quote(t) + ")"
}
