package sokelgen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

// 生成器的第一条底线：产出的必须是**合法 Go 源码**。
// 断言片段容易写得又长又脆，先用 parser 兜住语法——拼串生成最容易栽在引号转义、
// 中文标签、嵌套结构这些地方，而那类错误在字符串断言里看不出来。
func TestRenderContractCompiles(t *testing.T) {
	ops := []OpIO{{
		OpID: "send_message", InType: "SendMessageIn", OutType: "SendMessageOut",
		Inputs: []Field{
			{Name: "chat_id", Label: "对话 ID", Type: "string", Required: true, Desc: `带"引号"与反引号 ` + "`x`"},
			{Name: "count", Type: "number", Default: float64(3)},
			{Name: "mode", Type: "enum", Options: []Option{{Value: "a", Label: "甲"}, {Value: "b"}}},
			{Name: "slots", Type: "json", ValueType: &Field{Type: "json", Fields: []Field{{Name: "path", Type: "string"}}}},
			{Name: "blob", Type: "json", Opaque: true},
			{Name: "doc", Type: "json", OneOf: []OneOfVariant{
				{Name: "DocObject", Label: "文档对象", Type: "json", Fields: []Field{{Name: "title", Type: "string"}}},
			}},
		},
		Outputs: []Field{{Name: "ok", Type: "boolean"}},
	}}

	src, err := RenderContract("main", ops)
	if err != nil {
		t.Fatalf("渲染失败: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "zz_sokel.go", src, 0); err != nil {
		t.Fatalf("生成的代码语法不合法: %v\n---\n%s", err, src)
	}

	// 生成物必须自报身份，否则会被误当手写代码修改（改完下次生成即丢）
	if !strings.HasPrefix(src, "// Code generated by sokel-gen. DO NOT EDIT.") {
		t.Errorf("应有 generated 头: %.60s", src)
	}
	for _, want := range []string{
		`package main`,
		`func init()`,
		`"send_message"`,
		`SendMessageIn`, `SendMessageOut`,
		`Opaque: true`,
		`ValueType:`,
		`OneOf:`,
		`"甲"`,           // 中文标签原样带过去
		`sokel.TString`, // 类型用常量而非 sokel.ParamType("string")——生成物要进 code review
		`sokel.TEnum`,
		`Opaque:`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("生成物缺片段 %q\n---\n%s", want, src)
		}
	}
	// 引号与反引号必须正确转义，否则语法早就挂了——这里额外确认内容没被吃掉
	if !strings.Contains(src, `引号`) {
		t.Errorf("desc 内容丢失\n---\n%s", src)
	}
	// 数组元素不该重复写 sokel.Field（[]sokel.Field{} 里是冗余的，gofmt -s 的惯例）
	if strings.Contains(src, "sokel.Field{\n\t\t\t\tName:") {
		t.Errorf("数组元素不该带类型名前缀\n---\n%s", src)
	}
	// 确定性：同样输入两次渲染必须完全一致，否则每次生成都是无意义 diff
	again, _ := RenderContract("main", ops)
	if again != src {
		t.Error("渲染应确定性（两次结果不一致）")
	}
}

// 没有操作时不该产出一个空 init()——生成个空文件比不生成更让人困惑。
func TestRenderContractEmpty(t *testing.T) {
	if _, err := RenderContract("main", nil); err == nil {
		t.Fatal("无操作应报错而不是产出空文件")
	}
}
