// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"
)

// The generator's first floor: what comes out must be **valid Go source**. Fragment assertions get long
// and brittle, so the parser catches the syntax first — string concatenation trips most easily on quote
// escaping, non-ASCII labels and nested structures, and those failures are invisible to a string
// assertion.
func TestRenderContractCompiles(t *testing.T) {
	ops := []OpIO{{
		OpID: "send_message", InType: "SendMessageIn", OutType: "SendMessageOut",
		Inputs: []Field{
			{Name: "chat_id", Label: "对话 ID", Type: "string", Required: true, Desc: `with "quotes" and a backtick ` + "`x`"},
			{Name: "count", Type: "number", Default: float64(3)},
			{Name: "mode", Type: "enum", Options: []Option{{Value: "a", Label: "甲"}, {Value: "b"}}},
			{Name: "slots", Type: "json", ValueType: &Field{Type: "json", Fields: []Field{{Name: "path", Type: "string"}}}},
			{Name: "blob", Type: "json", Opaque: true},
			{Name: "doc", Type: "json", OneOf: []OneOfVariant{
				{Name: "DocObject", Label: "Document object", Type: "json", Fields: []Field{{Name: "title", Type: "string"}}},
			}},
		},
		Outputs: []Field{{Name: "ok", Type: "boolean"}},
	}}

	src, err := RenderContract("main", ops)
	if err != nil {
		t.Fatalf("rendering failed: %v", err)
	}
	if _, err := parser.ParseFile(token.NewFileSet(), "zz_sokel.go", src, 0); err != nil {
		t.Fatalf("the generated code is not syntactically valid: %v\n---\n%s", err, src)
	}

	// The output has to announce itself, or someone edits it as hand-written code and loses the change on
	// the next generation
	if !strings.HasPrefix(src, "// Code generated by sokel-gen. DO NOT EDIT.") {
		t.Errorf("a generated header is missing: %.60s", src)
	}
	for _, want := range []string{
		`package main`,
		`func init()`,
		`"send_message"`,
		`SendMessageIn`, `SendMessageOut`,
		`Opaque: true`,
		`ValueType:`,
		`OneOf:`,
		`"甲"`,           // a non-ASCII label passes through unchanged
		`sokel.TString`, // a constant rather than sokel.ParamType("string"); the output gets reviewed
		`sokel.TEnum`,
		`Opaque:`,
	} {
		if !strings.Contains(src, want) {
			t.Errorf("the output is missing fragment %q\n---\n%s", want, src)
		}
	}
	// Quotes and backticks must escape correctly, which the syntax check already covers; this confirms the
	// content was not swallowed
	if !strings.Contains(src, `quotes`) {
		t.Errorf("the desc content was lost\n---\n%s", src)
	}
	// Array elements should not repeat sokel.Field: inside []sokel.Field{} it is redundant, which is what
	// gofmt -s does
	if strings.Contains(src, "sokel.Field{\n\t\t\t\tName:") {
		t.Errorf("array elements should carry no type-name prefix\n---\n%s", src)
	}
	// Determinism: the same input rendered twice must match exactly, or every generation is a meaningless
	// diff
	again, _ := RenderContract("main", ops)
	if again != src {
		t.Error("rendering should be deterministic; the two results differ")
	}
}

// With no operations it should not produce an empty init(): an empty file is more confusing than none.
func TestRenderContractEmpty(t *testing.T) {
	if _, err := RenderContract("main", nil); err == nil {
		t.Fatal("no operations should fail rather than produce an empty file")
	}
}
