package sokelgen

// 从 sokel.yaml 渲染 TypeScript 插件的类型化外壳（interface + 注册口 + 触发口）。
//
// 与 RenderTS（导出给前端核对 UI schema 的执行契约表）不是一回事：那份是**给平台前端看的**，
// 这份是**给插件作者用的**——同一个 IR 的两个消费者，别把它们合成一个。
//
// 为什么不是 zod：zod schema 是运行时对象，用它声明契约就意味着「契约只有跑起来才知道」，
// 而且每种语言都得自己解释一遍那套 DSL。声明留在 sokel.yaml（语言中立），
// TS 这边只要类型——这也正是 TS 的强项：类型在编译期，运行时零开销。

import (
	"fmt"
	"sort"
	"strings"
)

// RenderTSPlugin 生成 TS 侧的全部类型化外壳。
func RenderTSPlugin(m *Manifest, doc string) (string, error) {
	cj, err := contractJSON(m, doc)
	if err != nil {
		return "", err
	}
	models := newModelSet()
	var body strings.Builder

	if m.Credential != nil && len(m.Credential.Fields) > 0 {
		body.WriteString(tsInterface("Credential", "凭证字段（平台随每次调用下发，插件从不落地）。", m.Credential.Fields, models, "Credential"))
	}

	ops := append([]OperationDecl(nil), m.Operations...)
	sort.Slice(ops, func(i, j int) bool { return ops[i].ID < ops[j].ID })
	for _, op := range ops {
		name := exportName(op.ID)
		body.WriteString(tsInterface(name+"In", opComment(op, "入参"), op.Inputs, models, name+"In"))
		body.WriteString(tsInterface(name+"Out", opComment(op, "出参"), op.Outputs, models, name+"Out"))
		body.WriteString(tsRegisterFn(op, name))
	}

	events := append([]EventDecl(nil), m.Events...)
	sort.Slice(events, func(i, j int) bool { return events[i].ID < events[j].ID })
	for _, e := range events {
		name := exportName(e.ID) + "Event"
		body.WriteString(tsInterface(name, orDefaultStr(e.Label, e.ID)+" 事件的 payload。", e.Fields, models, name))
		fn := "trigger" + exportName(e.ID)
		fmt.Fprintf(&body, "/** 推一条「%s」事件。eventId 是幂等键：同一条外部消息重复推只触发一次。 */\n", orDefaultStr(e.Label, e.ID))
		fmt.Fprintf(&body, "export function %s(ctx: SourceCtx, eventId: string, payload: %s): Promise<void> {\n", fn, name)
		fmt.Fprintf(&body, "  return ctx.trigger(%s, eventId, payload);\n}\n\n", jsonQuote(e.ID))
	}

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n//\n")
	b.WriteString("// 契约声明在 sokel.yaml —— 改字段请改那份，然后重新跑 `sokel-gen generate`。\n")
	b.WriteString("// 直接改本文件的话，下次生成就没了。\n\n")
	b.WriteString("import { Plugin } from \"@sokel-dev/plugin-sdk\";\n")
	b.WriteString("import type { Config, ContractData, Ctx, Emitter, SokelFile, SourceCtx } from \"@sokel-dev/plugin-sdk\";\n\n")
	b.WriteString("/** 上报给平台的契约（与 sokel.yaml 等价；三种语言的生成物里是同一份）。 */\n")
	b.WriteString("export const CONTRACT: ContractData = " + renderJSONLiteral(cj, 0) + ";\n\n")
	for _, name := range models.order {
		b.WriteString(models.rendered[name])
	}
	b.WriteString(body.String())
	b.WriteString("/** 按本契约建插件实例。 */\n")
	b.WriteString("export function newPlugin(cfg: Omit<Config, \"contract\"> = {}): Plugin {\n")
	b.WriteString("  return new Plugin({ contract: CONTRACT, ...cfg });\n}\n")
	return b.String(), nil
}

func tsRegisterFn(op OperationDecl, name string) string {
	var b strings.Builder
	fn := "on" + name
	if op.Stream {
		fmt.Fprintf(&b, "export type %sHandler = (ctx: Ctx, input: %sIn, out: Emitter<%sOut>) => Promise<void> | void;\n\n", name, name, name)
		fmt.Fprintf(&b, "/** 注册「%s」的实现（流式：用 out.text/out.json/out.vars 逐帧产出）。 */\n", orDefaultStr(op.Label, op.ID))
		fmt.Fprintf(&b, "export function %s(p: Plugin, fn: %sHandler): void {\n", fn, name)
		fmt.Fprintf(&b, "  p.register(%s, async (ctx, raw, out) => {\n", jsonQuote(op.ID))
		fmt.Fprintf(&b, "    await fn(ctx, raw as unknown as %sIn, out as Emitter<%sOut>);\n  });\n}\n\n", name, name)
		return b.String()
	}
	fmt.Fprintf(&b, "export type %sHandler = (ctx: Ctx, input: %sIn) => %sOut | void | Promise<%sOut | void>;\n\n", name, name, name, name)
	fmt.Fprintf(&b, "/** 注册「%s」的实现。 */\n", orDefaultStr(op.Label, op.ID))
	fmt.Fprintf(&b, "export function %s(p: Plugin, fn: %sHandler): void {\n", fn, name)
	fmt.Fprintf(&b, "  p.register(%s, async (ctx, raw, out) => {\n", jsonQuote(op.ID))
	fmt.Fprintf(&b, "    const res = await fn(ctx, raw as unknown as %sIn);\n", name)
	// 返回 void 也是合法实现：只做副作用的操作不必硬造一个空壳出参
	b.WriteString("    if (res) out.vars(res);\n  });\n}\n\n")
	return b.String()
}

// tsInterface 渲染一个 interface（连同它依赖的嵌套 interface）。
func tsInterface(name, doc string, fields []Field, models *modelSet, owner string) string {
	var b strings.Builder
	if doc != "" {
		b.WriteString("/**\n" + docComment(" * ", doc) + " */\n")
	}
	fmt.Fprintf(&b, "export interface %s {\n", name)
	for _, f := range fields {
		if c := strings.TrimSpace(f.Label + " " + f.Desc); c != "" {
			b.WriteString("  /** " + strings.ReplaceAll(c, "*/", "*\\/") + " */\n")
		}
		opt := "?"
		if f.Required {
			opt = ""
		}
		fmt.Fprintf(&b, "  %s%s: %s;\n", tsFieldName(f.Name), opt, tsType(f, owner, models))
	}
	if len(fields) == 0 {
		b.WriteString("  // 该操作没有字段\n")
	}
	b.WriteString("}\n\n")
	return b.String()
}

// tsFieldName：契约名直接当属性名。不是合法标识符时加引号——
// 属性名必须与线上的字段名逐字一致，改名等于换了个字段。
func tsFieldName(name string) string {
	for i, r := range name {
		ok := r == '_' || r == '$' || (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return jsonQuote(name)
		}
	}
	return name
}

func tsType(f Field, owner string, models *modelSet) string {
	if len(f.Types) > 1 {
		return "unknown" // 标量联合：unknown 逼调用方自己收窄，比 any 诚实
	}
	switch f.Type {
	case "number":
		return "number"
	case "boolean":
		return "boolean"
	case "file":
		return "SokelFile"
	case "enum":
		if len(f.Options) > 0 {
			opts := make([]string, 0, len(f.Options))
			for _, o := range f.Options {
				opts = append(opts, jsonQuote(o.Value))
			}
			return strings.Join(opts, " | ")
		}
		return "string"
	case "json":
		if len(f.OneOf) > 0 {
			return tsUnion(f, owner, models)
		}
		if f.Opaque {
			return "Record<string, unknown>"
		}
		if f.ValueType != nil {
			return "Record<string, " + tsType(*f.ValueType, owner, models) + ">"
		}
		if len(f.Fields) > 0 {
			return tsEnsure(modelNameOf(f, owner), f.Fields, models)
		}
		return "Record<string, unknown>"
	case "array":
		if len(f.OneOf) > 0 {
			return "Array<" + tsUnion(f, owner, models) + ">"
		}
		if f.ItemType == "file" {
			return "SokelFile[]"
		}
		if f.Opaque {
			return "unknown[]"
		}
		if len(f.Fields) > 0 {
			return tsEnsure(modelNameOf(f, owner), f.Fields, models) + "[]"
		}
		switch f.ItemType {
		case "number":
			return "number[]"
		case "boolean":
			return "boolean[]"
		case "string":
			return "string[]"
		}
		return "unknown[]"
	}
	return "string"
}

// tsUnion：结构联合。TS 的联合类型是这几种语言里最贴合协议的表达——
// 运行值就是分支本身的形状，收窄由 handler 自己按字段判别。
func tsUnion(f Field, owner string, models *modelSet) string {
	parts := make([]string, 0, len(f.OneOf))
	for _, v := range f.OneOf {
		name := variantModelName(v)
		switch {
		case len(v.Fields) > 0 && v.Type == "array":
			parts = append(parts, tsEnsure(name, v.Fields, models)+"[]")
		case len(v.Fields) > 0:
			parts = append(parts, tsEnsure(name, v.Fields, models))
		case v.Type == "array":
			parts = append(parts, "unknown[]")
		case v.Type == "number":
			parts = append(parts, "number")
		case v.Type == "boolean":
			parts = append(parts, "boolean")
		case v.Type == "json":
			parts = append(parts, "Record<string, unknown>")
		default:
			parts = append(parts, "string")
		}
	}
	return strings.Join(parts, " | ")
}

func tsEnsure(name string, fields []Field, models *modelSet) string {
	models.ensure(name, fields, func() {
		models.setRendered(name, tsInterface(name, "", fields, models, name))
	})
	return name
}
