// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// RenderSchema renders a contract back into schema declaration code, **for migrating existing
// plugins**.
//
// It generates the new declaration form from the existing struct+tag code (which the old AST parser can
// still read), so the result needs one human pass rather than eleven plugins transcribed by hand. That
// is what the old parser is still good for.
//
// What comes out is **a starting point, not a finished one**: the things a machine cannot read — which
// fields should really be Object/Any and why, which json should narrow to a concrete struct — need human
// judgement, so the file starts with a checklist.
func RenderSchema(pkg string, ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("there are no operations to migrate")
	}
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	// The named types being referenced: most of them currently live in package main and have to move to
	// the schema package along with the declaration.
	refs := map[string]bool{}
	for _, op := range sorted {
		collectRefs(op.Inputs, refs)
		collectRefs(op.Outputs, refs)
	}

	var b strings.Builder
	b.WriteString("// Reverse-generated by sokel-gen from an old struct+tag contract — **a starting point for the\n")
	b.WriteString("// migration, not the end of it**. Read it through before committing:\n")
	b.WriteString("//   1. Structureless json/array fields became Opaque(\"reason pending\"); decide one by one\n")
	b.WriteString("//      whether to declare the structure or write down why there is none\n")
	b.WriteString("//   2. The types referenced below must move from package main into this package — a schema\n")
	b.WriteString("//      only declares, and should not depend on the implementation\n")
	if len(refs) > 0 {
		names := make([]string, 0, len(refs))
		for n := range refs {
			names = append(names, n)
		}
		sort.Strings(names)
		b.WriteString("//      to move: " + strings.Join(names, ", ") + "\n")
	}
	b.WriteString("//   3. If a desc was carrying a \"value = meaning\" table (a list of voice ids, say), move those\n")
	b.WriteString("//      labels into field.Opt instead\n\n")
	b.WriteString("package " + pkg + "\n\n")
	b.WriteString("import (\n\t\"github.com/sokel-dev/sokel-plugin-sdk/sokel\"\n\t\"github.com/sokel-dev/sokel-plugin-sdk/sokel/field\"\n)\n\n")

	for _, op := range sorted {
		name := exportName(op.OpID)
		fmt.Fprintf(&b, "// %s %s\ntype %s struct{}\n\n", name, orDash(op.Label), name)
		fmt.Fprintf(&b, "func (%s) Meta() sokel.Meta {\n\treturn sokel.Meta{ID: %s", name, strconv.Quote(op.OpID))
		if op.Label != "" {
			fmt.Fprintf(&b, ", Label: %s", strconv.Quote(op.Label))
		}
		if op.Desc != "" {
			fmt.Fprintf(&b, ", Desc: %s", strconv.Quote(op.Desc))
		}
		if op.Stream {
			b.WriteString(", Stream: true")
		}
		b.WriteString("}\n}\n\n")
		writeSpecs(&b, name, "Inputs", op.Inputs)
		writeSpecs(&b, name, "Outputs", op.Outputs)
	}

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("the generated code will not format (most likely a rendering bug): %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

func collectRefs(fields []Field, out map[string]bool) {
	for _, f := range fields {
		if f.GoType != "" && !isIntGoType(f.GoType) { // an integer's GoType is not a type that needs moving
			out[f.GoType] = true
		}
		collectRefs(f.Fields, out)
	}
}

func writeSpecs(b *strings.Builder, typeName, method string, fields []Field) {
	fmt.Fprintf(b, "func (%s) %s() []sokel.FieldSpec {\n", typeName, method)
	if len(fields) == 0 {
		b.WriteString("\treturn nil\n}\n\n")
		return
	}
	b.WriteString("\treturn []sokel.FieldSpec{\n")
	for _, f := range fields {
		b.WriteString("\t\t" + fieldExpr(f) + ",\n")
	}
	b.WriteString("\t}\n}\n\n")
}

// fieldExpr turns one field into a chained field.Xxx(...) expression.
func fieldExpr(f Field) string {
	var e string
	switch f.Type {
	case "number":
		if isIntGoType(f.GoType) {
			e = fmt.Sprintf("field.Int(%s)", strconv.Quote(f.Name))
		} else {
			e = fmt.Sprintf("field.Number(%s)", strconv.Quote(f.Name))
		}
	case "boolean":
		e = fmt.Sprintf("field.Bool(%s)", strconv.Quote(f.Name))
	case "text":
		e = fmt.Sprintf("field.Text(%s)", strconv.Quote(f.Name))
	case "file":
		e = fmt.Sprintf("field.File(%s)", strconv.Quote(f.Name))
	case "enum":
		var opts []string
		for _, o := range f.Options {
			if o.Label != "" {
				opts = append(opts, fmt.Sprintf("field.Opt(%s, %s)", strconv.Quote(o.Value), strconv.Quote(o.Label)))
			} else {
				opts = append(opts, fmt.Sprintf("field.Opt(%s)", strconv.Quote(o.Value)))
			}
		}
		e = fmt.Sprintf("field.Enum(%s%s)", strconv.Quote(f.Name), prefixComma(strings.Join(opts, ", ")))
	case "json":
		switch {
		case f.Opaque || (len(f.Fields) == 0 && f.GoType == ""):
			// Structureless json in an old contract: the migration has to supply a reason, and the placeholder
			// forces someone to make that call
			e = fmt.Sprintf("field.Object(%s, \"reason pending\")", strconv.Quote(f.Name))
		case f.ValueType != nil:
			e = fmt.Sprintf("field.Json(%s, map[string]%s{})", strconv.Quote(f.Name), goScalarLiteral(f.ValueType.Type))
		case f.GoType != "":
			e = fmt.Sprintf("field.Json(%s, %s{})", strconv.Quote(f.Name), f.GoType)
		default:
			// An anonymous struct has no type to reference; leave a named one to be defined by hand
			e = fmt.Sprintf("field.Json(%s, struct{}{}) /* TODO: was an anonymous struct; define a named type */", strconv.Quote(f.Name))
		}
	case "array":
		switch {
		case f.ItemType == "file": // a file list (array<file>, the one and only spelling) has its own builder
			e = fmt.Sprintf("field.Files(%s)", strconv.Quote(f.Name))
		case f.GoType != "":
			e = fmt.Sprintf("field.Array(%s, []%s{})", strconv.Quote(f.Name), f.GoType)
		case f.ItemType != "":
			e = fmt.Sprintf("field.Array(%s, []%s{})", strconv.Quote(f.Name), goScalarLiteral(f.ItemType))
		case f.Opaque || len(f.Fields) == 0:
			e = fmt.Sprintf("field.Object(%s, \"reason pending\")", strconv.Quote(f.Name))
		default:
			e = fmt.Sprintf("field.Array(%s, []struct{}{}) /* TODO: element was an anonymous struct; define a named type */", strconv.Quote(f.Name))
		}
	default:
		e = fmt.Sprintf("field.String(%s)", strconv.Quote(f.Name))
	}

	if f.Label != "" {
		e += fmt.Sprintf(".Label(%s)", strconv.Quote(f.Label))
	}
	if f.Desc != "" {
		e += fmt.Sprintf(".Desc(%s)", strconv.Quote(f.Desc))
	}
	if f.Default != nil {
		e += ".Default(" + literalExpr(f.Default) + ")"
	} else if !f.Required {
		e += ".Optional()" // required by default, so optional must be explicit
	}
	return e
}

func literalExpr(v any) string {
	switch t := v.(type) {
	case string:
		return strconv.Quote(t)
	case bool:
		return strconv.FormatBool(t)
	case float64:
		return strconv.FormatFloat(t, 'g', -1, 64)
	}
	return strconv.Quote(fmt.Sprint(v))
}

func goScalarLiteral(t string) string {
	switch t {
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	}
	return "string"
}

func prefixComma(s string) string {
	if s == "" {
		return ""
	}
	return ", " + s
}

func orDash(s string) string {
	if s == "" {
		return "(migrated from an older contract)"
	}
	return s
}
