// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

// The TS render target: export the contract as an execution-contract table the frontend can import
// directly.
//
// Why only the execution contract and not the whole UI schema: they are **different models**. A UI
// schema describes how a person fills the node in — http splits one body into a kv list and a raw-text
// widget, and adds a credential picker and an output-structure declaration — whereas the execution
// contract describes which parameters a call takes. A serializer sits between them. Generating both
// from one place would inevitably distort one side.
//
// So only the latter is exported, and the frontend uses it to **cross-check** the hand-written UI
// schema (see the contract sweep in validation.test): every parameter the contract requires must have a
// matching required field or an explicit mapping on the UI side. "Added an op, forgot to mark it
// required" then turns a test red instead of waiting for a user to press Run.

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// RenderTS generates the TS execution-contract table.
func RenderTS(pkgLabel string, ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("there are no operations to export")
	}
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n//\n")
	b.WriteString("// The execution contract, from the schema declaration in " + pkgLabel + ".\n// Change it there, then regenerate.\n")
	b.WriteString("//\n// It carries only \"what a call takes\". How a human fills that in is a separate model:\n// widgets, grouping and split controls stay in the hand-written UI schema.\n")
	b.WriteString("// The frontend checks its hand-written schema against this: every required contract\n// parameter must have a matching required field or an explicit mapping.\n\n")
	b.WriteString("export interface KernelParam { name: string; type: string; required: boolean; itemType?: string }\n")
	b.WriteString("export interface KernelOp { label: string; inputs: KernelParam[]; outputs: KernelParam[] }\n\n")
	b.WriteString("export const KERNEL_OPS: Record<string, KernelOp> = {\n")
	for _, op := range sorted {
		b.WriteString("  " + strconv.Quote(op.OpID) + ": {\n")
		b.WriteString("    label: " + strconv.Quote(op.Label) + ",\n")
		b.WriteString("    inputs: " + tsParams(op.Inputs) + ",\n")
		b.WriteString("    outputs: " + tsParams(op.Outputs) + ",\n")
		b.WriteString("  },\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func tsParams(fs []Field) string {
	if len(fs) == 0 {
		return "[]"
	}
	var parts []string
	for _, f := range fs {
		// itemType is the array element type (array<file> and friends). Carry it through whenever the
		// contract has one: dropping it here cuts off the source of the frontend's arity check
		// (docs/type-system.md §11).
		if f.ItemType != "" {
			parts = append(parts, fmt.Sprintf("{ name: %s, type: %s, required: %v, itemType: %s }",
				strconv.Quote(f.Name), strconv.Quote(f.Type), f.Required, strconv.Quote(f.ItemType)))
			continue
		}
		parts = append(parts, fmt.Sprintf("{ name: %s, type: %s, required: %v }",
			strconv.Quote(f.Name), strconv.Quote(f.Type), f.Required))
	}
	return "[\n      " + strings.Join(parts, ",\n      ") + ",\n    ]"
}
