// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// RenderTypes 生成各操作的 In/Out struct。
//
// 每个字段同时带 json 与 **sokel** 两个 tag，值都是契约名。缺 sokel tag 的话，
// BindInput 会退回「Go 字段名转 snake_case」——契约名不是 snake_case 时就绑不上
// （p_http 的 responseType 落不进 ResponseType，file 模式静默走成文本模式）。
//
// 类型映射的两条原则：
//   - **能复用就复用**：声明时给了 Go 类型（field.Json("os", OSInfo{})），生成的字段就用
//     schema.OSInfo 本身，而不是照 Fields 重造一个等价结构——两个形状相同的类型互转
//     正是要杜绝的运行时转换。
//   - **说不清的就 any**：oneOf（Go 没有联合类型）与 opaque（本就无结构）都落 any。
//     包装类型的 switch Kind 也还是运行时判别，多包一层不如把「这里要自己判断」摆在明面上。
//
// sch 给出 schema 包的导入路径与包名前缀——二者不同（"a/b/schema" vs "schema"）。
func RenderTypes(pkg string, sch SchemaRef, ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("没有可生成的操作")
	}
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	var body strings.Builder
	need := &imports{}
	for _, op := range sorted {
		body.WriteString(renderStruct(op.InType, op.Inputs, qual(sch.Name), need))
		body.WriteString(renderStruct(op.OutType, op.Outputs, qual(sch.Name), need))
		// oneOf 的包装类型：每个带 oneOf 的字段一个
		body.WriteString(renderUnions(op.InType, op.Inputs, qual(sch.Name), need))
		body.WriteString(renderUnions(op.OutType, op.Outputs, qual(sch.Name), need))
	}

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// Input/output types are generated from the schema declaration.\n// Change a field there, then regenerate.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	// 只 import 真正用到的——多一个未使用的 import 就是编译失败。
	if need.sokel || need.schema || need.json {
		b.WriteString("import (\n")
		if need.json {
			b.WriteString("\t\"encoding/json\"\n\n")
		}
		if need.sokel {
			b.WriteString("\t\"github.com/sokel-dev/sokel-plugin-sdk/plugin\"\n")
		}
		if need.schema && sch.Import != "" {
			b.WriteString("\t" + strconv.Quote(sch.Import) + "\n")
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(body.String())

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("生成的代码无法格式化（多半是渲染有 bug）: %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// imports 记录本次渲染实际用到了哪些包。
type imports struct{ sokel, schema, json bool }

func renderStruct(name string, fields []Field, schemaPkg string, need *imports) string {
	owner := name
	var b strings.Builder
	fmt.Fprintf(&b, "type %s struct {\n", name)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%s %s `json:%s sokel:%s`\n",
			exportName(f.Name), goType(f, schemaPkg, owner, need, 1), strconv.Quote(f.Name), strconv.Quote(f.Name))
	}
	b.WriteString("}\n\n")
	return b.String()
}

func goType(f Field, schemaPkg, owner string, need *imports, depth int) string {
	// 联合类型（field.Any / type:"string,number"）：Go 里没有联合，只能是 any。
	// 这比按主类型生成诚实——按主类型生成的话，声明成 string|number 的字段会得到
	// 一个 string 变量，另一半值到不了手上。
	if len(f.Types) > 1 {
		return "any"
	}
	switch f.Type {
	case "number":
		// 整数提示（field.Int / 反射自 int 字段）：生成 int 而不是 float64，
		// 免得实现里每个数字字段都 float64(...) 转一道。契约里它仍是 number。
		if isIntGoType(f.GoType) {
			return f.GoType
		}
		return "float64"
	case "boolean":
		return "bool"
	case "file":
		need.sokel = true
		return "*plugin.File"
	case "json":
		// oneOf → 生成的包装类型（用户定案：any 太容易断言错）。
		// 名字由 owner + 字段名拼，owner 是所属的 In/Out 类型名。
		if len(f.OneOf) > 0 {
			return owner + exportName(f.Name)
		}
		// opaque：键值不定，但**类型仍是对象** —— 契约里 type=json 就是这个意思。
		// 生成 any 会连「是对象」这层也丢掉，handler 里还得先断言一次才能 range。
		if f.Opaque {
			return "map[string]any"
		}
		if f.GoType != "" && !isIntGoType(f.GoType) {
			need.schema = true
			return schemaPkg + f.GoType
		}
		if f.ValueType != nil {
			return "map[string]" + goType(*f.ValueType, schemaPkg, owner, need, depth)
		}
		if len(f.Fields) > 0 {
			return inlineStruct(f.Fields, schemaPkg, owner, need, depth)
		}
		return "any"
	case "array":
		// 元素是联合（field.ArrayOf）→ 元素用包装类型，字段是它的切片。
		// 与 json+oneOf 共用同一个包装类型，区别只在这里多一层 []。
		if len(f.OneOf) > 0 {
			return "[]" + owner + exportName(f.Name)
		}
		// 文件列表（array<file>，唯一表达）→ []*plugin.File。
		if f.ItemType == "file" {
			need.sokel = true
			return "[]*plugin.File"
		}
		if f.Opaque {
			return "[]any"
		}
		if isIntGoType(f.GoType) {
			return "[]" + f.GoType
		}
		if f.GoType != "" && !isIntGoType(f.GoType) {
			need.schema = true
			return "[]" + schemaPkg + f.GoType
		}
		if f.ItemType != "" {
			return "[]" + scalarGoType(f.ItemType)
		}
		if len(f.Fields) > 0 {
			return "[]" + inlineStruct(f.Fields, schemaPkg, owner, need, depth)
		}
		return "[]any"
	}
	return "string" // string / text / enum 都是字符串
}

// inlineStruct：没有具名 Go 类型可复用时（匿名结构声明），内联展开。
func inlineStruct(fields []Field, schemaPkg, owner string, need *imports, depth int) string {
	pad := strings.Repeat("\t", depth)
	var b strings.Builder
	b.WriteString("struct {\n")
	for _, f := range fields {
		fmt.Fprintf(&b, "%s\t%s %s `json:%s`\n",
			pad, exportName(f.Name), goType(f, schemaPkg, owner, need, depth+1), strconv.Quote(f.Name))
	}
	b.WriteString(pad + "}")
	return b.String()
}

func scalarGoType(t string) string {
	switch t {
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	}
	return "string"
}

// initialisms：Go 惯例里全大写的缩略词。不处理的话会生成出 KbId / Ok / Md5 这种，
// golint 会抱怨，读起来也别扭——生成的代码要和手写的一样地道。
// 取自 golint 的常用子集。
var initialisms = map[string]string{
	"api": "API", "ascii": "ASCII", "cpu": "CPU", "css": "CSS", "db": "DB", "dns": "DNS",
	"eof": "EOF", "guid": "GUID", "html": "HTML", "http": "HTTP", "https": "HTTPS",
	"id": "ID", "ids": "IDs", "ip": "IP", "json": "JSON", "lhs": "LHS", "llm": "LLM", "md5": "MD5", "ok": "OK",
	"os": "OS", "pid": "PID", "qps": "QPS", "ram": "RAM", "rhs": "RHS", "rpc": "RPC",
	"sha": "SHA", "sla": "SLA", "smtp": "SQL", "sql": "SQL", "ssh": "SSH", "tcp": "TCP",
	"tls": "TLS", "ttl": "TTL", "udp": "UDP", "ui": "UI", "uid": "UID", "uuid": "UUID",
	"uri": "URI", "url": "URL", "utf8": "UTF8", "vm": "VM", "xml": "XML", "xsrf": "XSRF",
}

// exportName：契约里的 snake_case → 导出的 CamelCase（json tag 保留原名）。
func exportName(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			b.WriteString(up)
			continue
		}
		r := []rune(p)
		if r[0] >= 'a' && r[0] <= 'z' {
			r[0] = r[0] - 'a' + 'A'
		}
		b.WriteString(string(r))
	}
	if b.Len() == 0 {
		return "Field"
	}
	return b.String()
}

// renderUnions 为带 oneOf 的字段生成包装类型。
//
// 形态是 raw + 类型化访问器，而不是「多字段指针」：后者要在 UnmarshalJSON 那一刻就判别
// 是哪个分支，而 oneOf 的运行值**不带 discriminator**（协议如此，否则下游引用路径要多一层），
// 按结构猜容易猜错。这里只收下原始字节，让 handler 按自己的顺序试——每次尝试都是确定类型的：
//
//	if doc, ok := in.Doc.AsDocObject(); ok { … }
//	if blocks, ok := in.Doc.AsBlocks(); ok { … }
//
// 都不匹配时用 Raw() 自己处理，不至于卡死。
func renderUnions(owner string, fields []Field, schemaPkg string, need *imports) string {
	var b strings.Builder
	for _, f := range fields {
		if len(f.OneOf) == 0 {
			continue
		}
		need.json = true
		name := owner + exportName(f.Name)
		fmt.Fprintf(&b, "// %s is the structural union behind %s.%s: one of the shapes below.\n",
			name, owner, exportName(f.Name))
		fmt.Fprintf(&b, "type %s struct{ raw json.RawMessage }\n\n", name)
		fmt.Fprintf(&b, "// UnmarshalJSON only keeps the raw bytes; the caller decides which branch to try.\n")
		fmt.Fprintf(&b, "func (u *%s) UnmarshalJSON(b []byte) error { u.raw = append(u.raw[:0], b...); return nil }\n\n", name)
		fmt.Fprintf(&b, "// MarshalJSON hands the bytes back untouched, so a round trip is lossless.\n")
		fmt.Fprintf(&b, "func (u %s) MarshalJSON() ([]byte, error) {\n\tif len(u.raw) == 0 {\n\t\treturn []byte(\"null\"), nil\n\t}\n\treturn u.raw, nil\n}\n\n", name)
		fmt.Fprintf(&b, "// Raw returns the raw bytes: the escape hatch when no branch matches.\n")
		fmt.Fprintf(&b, "func (u %s) Raw() json.RawMessage { return u.raw }\n\n", name)

		for _, v := range f.OneOf {
			gt := v.GoType
			if gt == "" {
				gt = v.Name // 旧契约没有 GoType 时退回 Name
			}
			vt := schemaPkg + gt
			need.schema = true
			ret, ptr := "*"+vt, "&out"
			if v.Type == "array" {
				ret, ptr = "[]"+vt, "out"
			}
			fmt.Fprintf(&b, "// As%s decodes it as %s; a shape mismatch returns false.\n", v.Name, v.Name)
			fmt.Fprintf(&b, "func (u %s) As%s() (%s, bool) {\n", name, v.Name, ret)
			if v.Type == "array" {
				fmt.Fprintf(&b, "\tvar out []%s\n", vt)
			} else {
				fmt.Fprintf(&b, "\tvar out %s\n", vt)
			}
			b.WriteString("\tif len(u.raw) == 0 || json.Unmarshal(u.raw, &out) != nil {\n\t\treturn nil, false\n\t}\n")
			fmt.Fprintf(&b, "\treturn %s, true\n}\n\n", ptr)
		}
	}
	return b.String()
}

// isIntGoType：GoType 是否为整数类型名。整数用 GoType 承载「其实是整数」的提示，
// 与「复用具名结构」共用这个字段——靠名字区分即可，不必再加一个字段。
func isIntGoType(s string) bool {
	switch s {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		return true
	}
	return false
}
