// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

import (
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// RenderTypes generates the In/Out structs for every operation.
//
// Every field carries both a json and a **sokel** tag, each holding the contract name. Without the
// sokel tag BindInput falls back to "Go field name lowered to snake_case", which fails to bind
// whenever the contract name is not snake_case (p_http's responseType would miss ResponseType, and
// file mode would silently degrade to text mode).
//
// Two rules govern the type mapping:
//   - **Reuse whatever can be reused**: when the declaration names a Go type (field.Json("os",
//     OSInfo{})), the generated field uses schema.OSInfo itself rather than rebuilding an equivalent
//     struct from Fields — converting between two identically shaped types is exactly the runtime
//     conversion this is meant to eliminate.
//   - **Anything unspeakable becomes any**: oneOf (Go has no union type) and opaque (no structure to
//     begin with) both land on any. A wrapper type's switch on Kind is still a runtime discrimination,
//     so rather than add a layer it is better to leave "you have to decide here" in plain sight.
//
// sch supplies the schema package's import path and its name prefix — the two differ ("a/b/schema"
// vs "schema").
func RenderTypes(pkg string, sch SchemaRef, ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("there are no operations to generate")
	}
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	var body strings.Builder
	need := &imports{}
	for _, op := range sorted {
		body.WriteString(renderStruct(op.InType, op.Inputs, qual(sch.Name), need))
		body.WriteString(renderStruct(op.OutType, op.Outputs, qual(sch.Name), need))
		// Wrapper types for oneOf: one per field that declares a oneOf
		body.WriteString(renderUnions(op.InType, op.Inputs, qual(sch.Name), need))
		body.WriteString(renderUnions(op.OutType, op.Outputs, qual(sch.Name), need))
	}

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n")
	b.WriteString("//\n// Input/output types are generated from the schema declaration.\n// Change a field there, then regenerate.\n\n")
	b.WriteString("package " + pkg + "\n\n")
	// Import only what is actually used — one unused import is a compile error.
	if need.sokel || need.schema || need.json {
		b.WriteString("import (\n")
		if need.json {
			b.WriteString("\t\"encoding/json\"\n\n")
		}
		if need.sokel {
			b.WriteString("\t\"github.com/sokel-dev/sokel-plugin-sdk/plugin\"\n")
		}
		if need.schema && sch.Import != "" {
			b.WriteString("\t" + strconv.Quote(sch.Import) + "\n")
		}
		b.WriteString(")\n\n")
	}
	b.WriteString(body.String())

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("the generated code will not format (most likely a rendering bug): %w\n---\n%s", err, b.String())
	}
	return string(out), nil
}

// imports records which packages this render actually used.
type imports struct{ sokel, schema, json bool }

func renderStruct(name string, fields []Field, schemaPkg string, need *imports) string {
	owner := name
	var b strings.Builder
	fmt.Fprintf(&b, "type %s struct {\n", name)
	for _, f := range fields {
		fmt.Fprintf(&b, "\t%s %s `json:%s sokel:%s`\n",
			exportName(f.Name), goType(f, schemaPkg, owner, need, 1), strconv.Quote(f.Name), strconv.Quote(f.Name))
	}
	b.WriteString("}\n\n")
	return b.String()
}

func goType(f Field, schemaPkg, owner string, need *imports, depth int) string {
	// Union types (field.Any / type:"string,number"): Go has no unions, so any it is. That is more
	// honest than picking the primary type — doing so would give a field declared string|number a
	// string variable, and half of its possible values would never arrive.
	if len(f.Types) > 1 {
		return "any"
	}
	switch f.Type {
	case "number":
		// An integer hint (field.Int, or reflected off an int field) generates int rather than float64,
		// sparing the implementation a float64(...) conversion on every numeric field. In the contract it
		// is still a number.
		if isIntGoType(f.GoType) {
			return f.GoType
		}
		return "float64"
	case "boolean":
		return "bool"
	case "file":
		need.sokel = true
		return "*plugin.File"
	case "json":
		// oneOf becomes a generated wrapper type (a decision made because any is far too easy to assert
		// wrongly). The name is owner + field name, where owner is the enclosing In/Out type.
		if len(f.OneOf) > 0 {
			return owner + exportName(f.Name)
		}
		// opaque: the keys are open-ended, but **the type is still an object** — that is what type=json
		// means in the contract. Generating any would throw away even that much, forcing the handler to
		// assert once before it can range.
		if f.Opaque {
			return "map[string]any"
		}
		if f.GoType != "" && !isIntGoType(f.GoType) {
			need.schema = true
			return schemaPkg + f.GoType
		}
		if f.ValueType != nil {
			return "map[string]" + goType(*f.ValueType, schemaPkg, owner, need, depth)
		}
		if len(f.Fields) > 0 {
			return inlineStruct(f.Fields, schemaPkg, owner, need, depth)
		}
		return "any"
	case "array":
		// A union element (field.ArrayOf) gets the wrapper type as its element, and the field is a slice
		// of it — the same wrapper as json+oneOf, differing only by this one [] layer.
		if len(f.OneOf) > 0 {
			return "[]" + owner + exportName(f.Name)
		}
		// A file list (array<file>, the one and only spelling) becomes []*plugin.File.
		if f.ItemType == "file" {
			need.sokel = true
			return "[]*plugin.File"
		}
		if f.Opaque {
			return "[]any"
		}
		if isIntGoType(f.GoType) {
			return "[]" + f.GoType
		}
		if f.GoType != "" && !isIntGoType(f.GoType) {
			need.schema = true
			return "[]" + schemaPkg + f.GoType
		}
		if f.ItemType != "" {
			return "[]" + scalarGoType(f.ItemType)
		}
		if len(f.Fields) > 0 {
			return "[]" + inlineStruct(f.Fields, schemaPkg, owner, need, depth)
		}
		return "[]any"
	}
	return "string" // string, text and enum are all strings
}

// inlineStruct expands a declaration inline when there is no named Go type to reuse (an anonymous
// struct declaration).
func inlineStruct(fields []Field, schemaPkg, owner string, need *imports, depth int) string {
	pad := strings.Repeat("\t", depth)
	var b strings.Builder
	b.WriteString("struct {\n")
	for _, f := range fields {
		fmt.Fprintf(&b, "%s\t%s %s `json:%s`\n",
			pad, exportName(f.Name), goType(f, schemaPkg, owner, need, depth+1), strconv.Quote(f.Name))
	}
	b.WriteString(pad + "}")
	return b.String()
}

func scalarGoType(t string) string {
	switch t {
	case "number":
		return "float64"
	case "boolean":
		return "bool"
	}
	return "string"
}

// initialisms are the acronyms Go convention writes in full caps. Without this the generator would
// produce KbId / Ok / Md5, which golint complains about and which read badly — generated code should
// be as idiomatic as hand-written code. This is golint's common subset.
var initialisms = map[string]string{
	"api": "API", "ascii": "ASCII", "cpu": "CPU", "css": "CSS", "db": "DB", "dns": "DNS",
	"eof": "EOF", "guid": "GUID", "html": "HTML", "http": "HTTP", "https": "HTTPS",
	"id": "ID", "ids": "IDs", "ip": "IP", "json": "JSON", "lhs": "LHS", "llm": "LLM", "md5": "MD5", "ok": "OK",
	"os": "OS", "pid": "PID", "qps": "QPS", "ram": "RAM", "rhs": "RHS", "rpc": "RPC",
	"sha": "SHA", "sla": "SLA", "smtp": "SQL", "sql": "SQL", "ssh": "SSH", "tcp": "TCP",
	"tls": "TLS", "ttl": "TTL", "udp": "UDP", "ui": "UI", "uid": "UID", "uuid": "UUID",
	"uri": "URI", "url": "URL", "utf8": "UTF8", "vm": "VM", "xml": "XML", "xsrf": "XSRF",
}

// exportName turns the contract's snake_case into an exported CamelCase name (the json tag keeps the
// original).
func exportName(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		if up, ok := initialisms[strings.ToLower(p)]; ok {
			b.WriteString(up)
			continue
		}
		r := []rune(p)
		if r[0] >= 'a' && r[0] <= 'z' {
			r[0] = r[0] - 'a' + 'A'
		}
		b.WriteString(string(r))
	}
	if b.Len() == 0 {
		return "Field"
	}
	return b.String()
}

// renderUnions generates the wrapper types for fields that declare a oneOf.
//
// The shape is raw bytes plus typed accessors rather than "one pointer per branch": the latter would
// have to decide which branch it is at UnmarshalJSON time, and a oneOf's runtime value carries **no
// discriminator** (the protocol says so — otherwise downstream reference paths would need one more
// level), so guessing from the structure guesses wrong. This keeps the raw bytes and lets the handler
// try branches in whatever order it likes, each attempt landing on a definite type:
//
//	if doc, ok := in.Doc.AsDocObject(); ok { … }
//	if blocks, ok := in.Doc.AsBlocks(); ok { … }
//
// If nothing matches, Raw() lets the handler cope on its own instead of being stuck.
func renderUnions(owner string, fields []Field, schemaPkg string, need *imports) string {
	var b strings.Builder
	for _, f := range fields {
		if len(f.OneOf) == 0 {
			continue
		}
		need.json = true
		name := owner + exportName(f.Name)
		fmt.Fprintf(&b, "// %s is the structural union behind %s.%s: one of the shapes below.\n",
			name, owner, exportName(f.Name))
		fmt.Fprintf(&b, "type %s struct{ raw json.RawMessage }\n\n", name)
		fmt.Fprintf(&b, "// UnmarshalJSON only keeps the raw bytes; the caller decides which branch to try.\n")
		fmt.Fprintf(&b, "func (u *%s) UnmarshalJSON(b []byte) error { u.raw = append(u.raw[:0], b...); return nil }\n\n", name)
		fmt.Fprintf(&b, "// MarshalJSON hands the bytes back untouched, so a round trip is lossless.\n")
		fmt.Fprintf(&b, "func (u %s) MarshalJSON() ([]byte, error) {\n\tif len(u.raw) == 0 {\n\t\treturn []byte(\"null\"), nil\n\t}\n\treturn u.raw, nil\n}\n\n", name)
		fmt.Fprintf(&b, "// Raw returns the raw bytes: the escape hatch when no branch matches.\n")
		fmt.Fprintf(&b, "func (u %s) Raw() json.RawMessage { return u.raw }\n\n", name)

		for _, v := range f.OneOf {
			gt := v.GoType
			if gt == "" {
				gt = v.Name // older contracts have no GoType; fall back to Name
			}
			vt := schemaPkg + gt
			need.schema = true
			ret, ptr := "*"+vt, "&out"
			if v.Type == "array" {
				ret, ptr = "[]"+vt, "out"
			}
			fmt.Fprintf(&b, "// As%s decodes it as %s; a shape mismatch returns false.\n", v.Name, v.Name)
			fmt.Fprintf(&b, "func (u %s) As%s() (%s, bool) {\n", name, v.Name, ret)
			if v.Type == "array" {
				fmt.Fprintf(&b, "\tvar out []%s\n", vt)
			} else {
				fmt.Fprintf(&b, "\tvar out %s\n", vt)
			}
			b.WriteString("\tif len(u.raw) == 0 || json.Unmarshal(u.raw, &out) != nil {\n\t\treturn nil, false\n\t}\n")
			fmt.Fprintf(&b, "\treturn %s, true\n}\n\n", ptr)
		}
	}
	return b.String()
}

// isIntGoType reports whether GoType names an integer type. Integers use GoType to carry the "this is
// really an integer" hint, sharing the field with "reuse this named struct" — the name alone tells them
// apart, so no extra field is needed.
func isIntGoType(s string) bool {
	switch s {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		return true
	}
	return false
}
