// Copyright 2026 The Sokel Authors
// SPDX-License-Identifier: Apache-2.0

package sokelgen

// TS 渲染目标：把契约导出成前端能直接 import 的执行契约表。
//
// 为什么只导「执行契约」而不是整个 UI schema：两者是**不同的模型**。
// UI schema 描述的是「怎么让人填」——http 把一个 body 拆成 kv 列表与原文两个控件、
// 额外有凭证选择器和输出结构声明；执行契约描述的是「调用要哪些参数」。
// 中间隔着一层 serializer。硬要一处生成两者，必然逼着某一边变形。
//
// 所以这里只导后者，前端拿它去**核对**手写的 UI schema（见 validation.test 的契约巡检）：
// 契约要求非空的参数，UI 那侧必须有对应的必填字段或显式映射。
// 「加了 op 忘了标必填」于是在测试里红，而不是等用户点运行。

import (
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// RenderTS 生成 TS 执行契约表。
func RenderTS(pkgLabel string, ops []OpIO) (string, error) {
	if len(ops) == 0 {
		return "", fmt.Errorf("没有可导出的操作")
	}
	sorted := append([]OpIO(nil), ops...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].OpID < sorted[j].OpID })

	var b strings.Builder
	b.WriteString("// Code generated by sokel-gen. DO NOT EDIT.\n//\n")
	b.WriteString("// The execution contract, from the schema declaration in " + pkgLabel + ".\n// Change it there, then regenerate.\n")
	b.WriteString("//\n// It carries only \"what a call takes\". How a human fills that in is a separate model:\n// widgets, grouping and split controls stay in the hand-written UI schema.\n")
	b.WriteString("// The frontend checks its hand-written schema against this: every required contract\n// parameter must have a matching required field or an explicit mapping.\n\n")
	b.WriteString("export interface KernelParam { name: string; type: string; required: boolean; itemType?: string }\n")
	b.WriteString("export interface KernelOp { label: string; inputs: KernelParam[]; outputs: KernelParam[] }\n\n")
	b.WriteString("export const KERNEL_OPS: Record<string, KernelOp> = {\n")
	for _, op := range sorted {
		b.WriteString("  " + strconv.Quote(op.OpID) + ": {\n")
		b.WriteString("    label: " + strconv.Quote(op.Label) + ",\n")
		b.WriteString("    inputs: " + tsParams(op.Inputs) + ",\n")
		b.WriteString("    outputs: " + tsParams(op.Outputs) + ",\n")
		b.WriteString("  },\n")
	}
	b.WriteString("}\n")
	return b.String(), nil
}

func tsParams(fs []Field) string {
	if len(fs) == 0 {
		return "[]"
	}
	var parts []string
	for _, f := range fs {
		// itemType：数组元素类型（array<file> 等）。契约有就带上——丢在这一层，
		// 前端的数量位校验（docs/type-system.md §11）就断了源头。
		if f.ItemType != "" {
			parts = append(parts, fmt.Sprintf("{ name: %s, type: %s, required: %v, itemType: %s }",
				strconv.Quote(f.Name), strconv.Quote(f.Type), f.Required, strconv.Quote(f.ItemType)))
			continue
		}
		parts = append(parts, fmt.Sprintf("{ name: %s, type: %s, required: %v }",
			strconv.Quote(f.Name), strconv.Quote(f.Type), f.Required))
	}
	return "[\n      " + strings.Join(parts, ",\n      ") + ",\n    ]"
}
