// Code generated by sokel-gen. DO NOT EDIT.
//
// 契约声明在 sokel.yaml —— 改字段请改那份，然后重新跑 `sokel-gen generate`。
// 直接改本文件的话，下次生成就没了。

import { Plugin } from "@sokel-dev/plugin-sdk";
import type { Config, ContractData, Ctx, Emitter, SokelFile, SourceCtx } from "@sokel-dev/plugin-sdk";

/** 上报给平台的契约（与 sokel.yaml 等价；三种语言的生成物里是同一份）。 */
export const CONTRACT: ContractData = {
  "auth_flow": {
    "kind": "input",
    "steps": [
      "start",
      "poll",
      "submit"
    ]
  },
  "capabilities": {
    "recency": false
  },
  "credential_schema": [
    {
      "label": "API Key",
      "name": "api_key",
      "required": true,
      "type": "secret"
    },
    {
      "default": "https://api.example.com",
      "label": "服务地址",
      "name": "base_url",
      "type": "string"
    },
    {
      "default": "cn",
      "label": "区域",
      "name": "region",
      "options": [
        {
          "label": "中国大陆",
          "value": "cn"
        },
        {
          "label": "新加坡",
          "value": "sg"
        }
      ],
      "type": "enum"
    }
  ],
  "desc": "覆盖全部字段形态、文件、流式、事件、webhook 与协作式认证的参考插件",
  "doc": "# 全能示例（kitchen-sink）\n\n这是一个**参考插件**：它不干实际的活，但把 Sokel 插件能声明的东西各演示了一遍。\n用它验证连通性、对照写法，或作为新插件的起点。\n\n## 凭证\n\n| 字段 | 说明 |\n|---|---|\n| API Key | 必填，脱敏存储 |\n| 服务地址 | 默认 `https://api.example.com` |\n| 区域 | 中国大陆 / 新加坡 |\n\n凭证行上有「登录」按钮：点开后插件出一道题（本例是让你回填一个验证码，\n任意 6 位数字都算通过），面板轮询到确认后把会话写回凭证。\n\n## 操作\n\n- **回显全部形态** —— 每种入参形态各一份（文本、数字、布尔、枚举、数组、嵌套对象、\n  动态键、结构联合、透传 JSON），原样回显。用来确认「契约怎么声明，运行值就长什么样」。\n- **文件摘要** —— 传一个文件，返回它的 SHA-256 与字节数，并产出一份报告文件。\n  文件在画布里只流转引用，字节走插件与平台之间的分块通道。\n- **流式回话** —— 逐帧产出文本（节点执行时能实时看到），末尾给下游一个类型化的输出对象。\n- **凭证体检** —— 平台约定的 `health_check`：凭证页点「测试」调的就是它。本例校验\n  API Key 是不是 `sk-` 开头，不是就报「不可用」并说清原因。\n\n## 事件\n\n插件会推两种事件，可用作工作流的触发器：\n\n- **收到消息** —— 由 webhook 入站触发（把凭证的 webhook 入口配到上游系统即可）。\n- **心跳** —— 事件源每 30 秒推一条，用来确认「插件推、平台起流」这条链路是通的。\n\n两种事件都带 `chat_id`，它是公共字段，在触发节点的输出里可以直接引用。\n\n## Webhook\n\n在凭证行上开一个 webhook 入口，把得到的地址配到上游系统。插件会校验\n`X-Sokel-Token` 头（值取凭证里的 API Key），校验通过才推事件——校验失败返回 401。\n",
  "events": [
    {
      "desc": "上游 webhook 或长轮询拿到的一条消息",
      "fields": [
        {
          "label": "会话 ID",
          "name": "chat_id",
          "required": true,
          "type": "string"
        },
        {
          "label": "文本",
          "name": "text",
          "type": "string"
        },
        {
          "label": "附件",
          "name": "attachment",
          "type": "file"
        }
      ],
      "id": "message",
      "label": "收到消息"
    },
    {
      "desc": "事件源存活信号，用来验证「插件推、平台起流」这条链路",
      "fields": [
        {
          "label": "会话 ID",
          "name": "chat_id",
          "required": true,
          "type": "string"
        },
        {
          "label": "时刻",
          "name": "at",
          "required": true,
          "type": "string"
        }
      ],
      "id": "heartbeat",
      "label": "心跳"
    }
  ],
  "events_common": [
    {
      "label": "会话 ID",
      "name": "chat_id",
      "required": true,
      "type": "string"
    }
  ],
  "label": "全能示例",
  "name": "kitchen-sink",
  "operations": [
    {
      "desc": "每种字段形态各一份，原样回显——契约怎么声明、运行值就长什么样。",
      "id": "echo_all",
      "inputs": [
        {
          "label": "文本",
          "name": "text",
          "required": true,
          "type": "string"
        },
        {
          "desc": "多行文本；与 string 的区别只在 UI 控件",
          "label": "备注",
          "name": "note",
          "type": "text"
        },
        {
          "default": 1,
          "goType": "int",
          "label": "次数",
          "name": "count",
          "type": "number"
        },
        {
          "default": 0.5,
          "label": "比例",
          "name": "ratio",
          "type": "number"
        },
        {
          "default": true,
          "label": "开关",
          "name": "flag",
          "type": "boolean"
        },
        {
          "default": "fast",
          "label": "模式",
          "name": "mode",
          "options": [
            {
              "label": "快（少调一次上游）",
              "value": "fast"
            },
            {
              "label": "全（更慢但更全）",
              "value": "full"
            }
          ],
          "type": "enum"
        },
        {
          "itemType": "string",
          "label": "标签",
          "name": "tags",
          "type": "array"
        },
        {
          "fields": [
            {
              "label": "姓名",
              "name": "name",
              "required": true,
              "type": "string"
            },
            {
              "goType": "int",
              "label": "年龄",
              "name": "age",
              "type": "number"
            },
            {
              "fields": [
                {
                  "label": "城市",
                  "name": "city",
                  "type": "string"
                },
                {
                  "label": "邮编",
                  "name": "zip",
                  "type": "string"
                }
              ],
              "label": "地址",
              "name": "address",
              "type": "json"
            }
          ],
          "goType": "Profile",
          "label": "档案",
          "name": "profile",
          "type": "json"
        },
        {
          "fields": [
            {
              "label": "X",
              "name": "x",
              "required": true,
              "type": "number"
            },
            {
              "label": "Y",
              "name": "y",
              "required": true,
              "type": "number"
            }
          ],
          "goType": "Point",
          "label": "坐标集",
          "name": "points",
          "type": "array"
        },
        {
          "desc": "键运行期才知道、值类型统一",
          "label": "动态标签",
          "name": "labels",
          "type": "json",
          "valueType": {
            "name": "value",
            "type": "string"
          }
        },
        {
          "desc": "调用方透传，形状由上游决定——无结构必须写清理由，否则不允许标 opaque",
          "label": "透传",
          "name": "extra",
          "opaque": true,
          "type": "json"
        },
        {
          "desc": "结构联合：三种形状之一，运行值就是该分支本身（不带 discriminator 包装）",
          "label": "文档",
          "name": "doc",
          "oneOf": [
            {
              "fields": [
                {
                  "label": "标题",
                  "name": "title",
                  "required": true,
                  "type": "string"
                },
                {
                  "label": "正文",
                  "name": "body",
                  "type": "text"
                }
              ],
              "label": "文档对象",
              "name": "DocObject",
              "type": "json"
            },
            {
              "fields": [
                {
                  "label": "类型",
                  "name": "kind",
                  "required": true,
                  "type": "string"
                },
                {
                  "label": "内容",
                  "name": "content",
                  "type": "string"
                }
              ],
              "label": "块数组",
              "name": "Block",
              "type": "array"
            }
          ],
          "type": "json"
        }
      ],
      "label": "回显全部形态",
      "outputs": [
        {
          "label": "文本",
          "name": "text",
          "required": true,
          "type": "string"
        },
        {
          "goType": "int",
          "label": "次数",
          "name": "count",
          "required": true,
          "type": "number"
        },
        {
          "label": "模式",
          "name": "mode",
          "required": true,
          "type": "string"
        },
        {
          "itemType": "string",
          "label": "标签",
          "name": "tags",
          "type": "array"
        },
        {
          "fields": [
            {
              "label": "姓名",
              "name": "name",
              "required": true,
              "type": "string"
            },
            {
              "goType": "int",
              "label": "年龄",
              "name": "age",
              "type": "number"
            },
            {
              "fields": [
                {
                  "label": "城市",
                  "name": "city",
                  "type": "string"
                },
                {
                  "label": "邮编",
                  "name": "zip",
                  "type": "string"
                }
              ],
              "label": "地址",
              "name": "address",
              "type": "json"
            }
          ],
          "goType": "Profile",
          "label": "档案",
          "name": "profile",
          "type": "json"
        },
        {
          "fields": [
            {
              "label": "X",
              "name": "x",
              "required": true,
              "type": "number"
            },
            {
              "label": "Y",
              "name": "y",
              "required": true,
              "type": "number"
            }
          ],
          "goType": "Point",
          "label": "坐标集",
          "name": "points",
          "type": "array"
        },
        {
          "label": "动态标签",
          "name": "labels",
          "type": "json",
          "valueType": {
            "name": "value",
            "type": "string"
          }
        },
        {
          "label": "摘要",
          "name": "summary",
          "required": true,
          "type": "text"
        }
      ]
    },
    {
      "desc": "平台约定的保留 id：凭证页的「测试」与工作流的「检查凭证」都调它，不带入参。 凭证不可用要**返回 ok=false**，不是报错——报错的话平台只能说「调用失败」， 说不出是密钥过期还是网络不通。没声明这个操作的插件，凭证只能靠实际调用来发现失效。",
      "id": "health_check",
      "inputs": [],
      "label": "凭证体检",
      "outputs": [
        {
          "label": "可用",
          "name": "ok",
          "required": true,
          "type": "boolean"
        },
        {
          "desc": "不可用时说清原因（人话），可用时可留空",
          "label": "说明",
          "name": "message",
          "type": "string"
        }
      ]
    },
    {
      "desc": "文件入参 → 惰性取字节；产出文件 → 字节交回平台登记，画布里只流转引用。",
      "id": "file_digest",
      "inputs": [
        {
          "label": "文件",
          "name": "file",
          "required": true,
          "type": "file"
        },
        {
          "desc": "数量位只有 array<file> 这一种表达",
          "itemType": "file",
          "label": "附加文件",
          "name": "extras",
          "type": "array"
        }
      ],
      "label": "文件摘要",
      "outputs": [
        {
          "label": "文件名",
          "name": "name",
          "required": true,
          "type": "string"
        },
        {
          "label": "摘要",
          "name": "sha256",
          "required": true,
          "type": "string"
        },
        {
          "goType": "int",
          "label": "字节数",
          "name": "size",
          "required": true,
          "type": "number"
        },
        {
          "goType": "int",
          "label": "附加文件数",
          "name": "extra_count",
          "required": true,
          "type": "number"
        },
        {
          "label": "报告文件",
          "name": "report",
          "type": "file"
        }
      ],
      "timeoutSec": 120
    },
    {
      "desc": "流式操作：逐帧产出文本给人看，末尾产出类型化变量给下游。",
      "id": "chat_stream",
      "inputs": [
        {
          "label": "提示词",
          "name": "prompt",
          "required": true,
          "type": "string"
        },
        {
          "default": 3,
          "goType": "int",
          "label": "分几帧",
          "name": "chunks",
          "type": "number"
        }
      ],
      "label": "流式回话",
      "outputs": [
        {
          "label": "回复",
          "name": "reply",
          "required": true,
          "type": "text"
        },
        {
          "goType": "int",
          "label": "帧数",
          "name": "frames",
          "required": true,
          "type": "number"
        }
      ],
      "stream": true
    },
    {
      "id": "auth.start",
      "inputs": [],
      "internal": true,
      "label": "发起认证",
      "outputs": [
        {
          "label": "认证 id",
          "name": "auth_id",
          "required": true,
          "type": "string"
        },
        {
          "desc": "挑战内容由 kind 决定：qr 给 qr_image，input 给 prompt",
          "label": "认证挑战",
          "name": "challenge",
          "opaque": true,
          "required": true,
          "type": "json"
        },
        {
          "goType": "int",
          "label": "有效期(秒)",
          "name": "expires_in",
          "type": "number"
        }
      ]
    },
    {
      "id": "auth.poll",
      "inputs": [
        {
          "label": "认证 id",
          "name": "auth_id",
          "required": true,
          "type": "string"
        }
      ],
      "internal": true,
      "label": "轮询认证状态",
      "outputs": [
        {
          "desc": "pending / scanned / confirmed / expired",
          "label": "状态",
          "name": "status",
          "required": true,
          "type": "string"
        },
        {
          "desc": "confirmed 时的凭证内容，形状由插件自定；平台写入凭证行后剥离",
          "label": "会话",
          "name": "session",
          "opaque": true,
          "type": "json"
        }
      ]
    },
    {
      "id": "auth.submit",
      "inputs": [
        {
          "label": "认证 id",
          "name": "auth_id",
          "required": true,
          "type": "string"
        },
        {
          "label": "用户输入",
          "name": "input",
          "required": true,
          "type": "string"
        }
      ],
      "internal": true,
      "label": "提交认证输入",
      "outputs": [
        {
          "label": "已提交",
          "name": "ok",
          "required": true,
          "type": "boolean"
        }
      ]
    }
  ],
  "version": "1.0.0"
};

export interface ProfileAddress {
  /** 城市 */
  city?: string;
  /** 邮编 */
  zip?: string;
}

export interface Profile {
  /** 姓名 */
  name: string;
  /** 年龄 */
  age?: number;
  /** 地址 */
  address?: ProfileAddress;
}

export interface Point {
  /** X */
  x: number;
  /** Y */
  y: number;
}

export interface DocObject {
  /** 标题 */
  title: string;
  /** 正文 */
  body?: string;
}

export interface Block {
  /** 类型 */
  kind: string;
  /** 内容 */
  content?: string;
}

/**
 * 凭证字段（平台随每次调用下发，插件从不落地）。
 */
export interface Credential {
  /** API Key */
  api_key: string;
  /** 服务地址 */
  base_url?: string;
  /** 区域 */
  region?: "cn" | "sg";
}

/**
 * 流式回话 的入参。
 *
 * 流式操作：逐帧产出文本给人看，末尾产出类型化变量给下游。
 */
export interface ChatStreamIn {
  /** 提示词 */
  prompt: string;
  /** 分几帧 */
  chunks?: number;
}

/**
 * 流式回话 的出参。
 *
 * 流式操作：逐帧产出文本给人看，末尾产出类型化变量给下游。
 */
export interface ChatStreamOut {
  /** 回复 */
  reply: string;
  /** 帧数 */
  frames: number;
}

export type ChatStreamHandler = (ctx: Ctx, input: ChatStreamIn, out: Emitter<ChatStreamOut>) => Promise<void> | void;

/** 注册「流式回话」的实现（流式：用 out.text/out.json/out.vars 逐帧产出）。 */
export function onChatStream(p: Plugin, fn: ChatStreamHandler): void {
  p.register("chat_stream", async (ctx, raw, out) => {
    await fn(ctx, raw as unknown as ChatStreamIn, out as Emitter<ChatStreamOut>);
  });
}

/**
 * 回显全部形态 的入参。
 *
 * 每种字段形态各一份，原样回显——契约怎么声明、运行值就长什么样。
 */
export interface EchoAllIn {
  /** 文本 */
  text: string;
  /** 备注 多行文本；与 string 的区别只在 UI 控件 */
  note?: string;
  /** 次数 */
  count?: number;
  /** 比例 */
  ratio?: number;
  /** 开关 */
  flag?: boolean;
  /** 模式 */
  mode?: "fast" | "full";
  /** 标签 */
  tags?: string[];
  /** 档案 */
  profile?: Profile;
  /** 坐标集 */
  points?: Point[];
  /** 动态标签 键运行期才知道、值类型统一 */
  labels?: Record<string, string>;
  /** 透传 调用方透传，形状由上游决定——无结构必须写清理由，否则不允许标 opaque */
  extra?: Record<string, unknown>;
  /** 文档 结构联合：三种形状之一，运行值就是该分支本身（不带 discriminator 包装） */
  doc?: DocObject | Block[];
}

/**
 * 回显全部形态 的出参。
 *
 * 每种字段形态各一份，原样回显——契约怎么声明、运行值就长什么样。
 */
export interface EchoAllOut {
  /** 文本 */
  text: string;
  /** 次数 */
  count: number;
  /** 模式 */
  mode: string;
  /** 标签 */
  tags?: string[];
  /** 档案 */
  profile?: Profile;
  /** 坐标集 */
  points?: Point[];
  /** 动态标签 */
  labels?: Record<string, string>;
  /** 摘要 */
  summary: string;
}

export type EchoAllHandler = (ctx: Ctx, input: EchoAllIn) => EchoAllOut | void | Promise<EchoAllOut | void>;

/** 注册「回显全部形态」的实现。 */
export function onEchoAll(p: Plugin, fn: EchoAllHandler): void {
  p.register("echo_all", async (ctx, raw, out) => {
    const res = await fn(ctx, raw as unknown as EchoAllIn);
    if (res) out.vars(res);
  });
}

/**
 * 文件摘要 的入参。
 *
 * 文件入参 → 惰性取字节；产出文件 → 字节交回平台登记，画布里只流转引用。
 */
export interface FileDigestIn {
  /** 文件 */
  file: SokelFile;
  /** 附加文件 数量位只有 array<file> 这一种表达 */
  extras?: SokelFile[];
}

/**
 * 文件摘要 的出参。
 *
 * 文件入参 → 惰性取字节；产出文件 → 字节交回平台登记，画布里只流转引用。
 */
export interface FileDigestOut {
  /** 文件名 */
  name: string;
  /** 摘要 */
  sha256: string;
  /** 字节数 */
  size: number;
  /** 附加文件数 */
  extra_count: number;
  /** 报告文件 */
  report?: SokelFile;
}

export type FileDigestHandler = (ctx: Ctx, input: FileDigestIn) => FileDigestOut | void | Promise<FileDigestOut | void>;

/** 注册「文件摘要」的实现。 */
export function onFileDigest(p: Plugin, fn: FileDigestHandler): void {
  p.register("file_digest", async (ctx, raw, out) => {
    const res = await fn(ctx, raw as unknown as FileDigestIn);
    if (res) out.vars(res);
  });
}

/**
 * 凭证体检 的入参。
 *
 * 平台约定的保留 id：凭证页的「测试」与工作流的「检查凭证」都调它，不带入参。 凭证不可用要**返回 ok=false**，不是报错——报错的话平台只能说「调用失败」， 说不出是密钥过期还是网络不通。没声明这个操作的插件，凭证只能靠实际调用来发现失效。
 */
export interface HealthCheckIn {
  // 该操作没有字段
}

/**
 * 凭证体检 的出参。
 *
 * 平台约定的保留 id：凭证页的「测试」与工作流的「检查凭证」都调它，不带入参。 凭证不可用要**返回 ok=false**，不是报错——报错的话平台只能说「调用失败」， 说不出是密钥过期还是网络不通。没声明这个操作的插件，凭证只能靠实际调用来发现失效。
 */
export interface HealthCheckOut {
  /** 可用 */
  ok: boolean;
  /** 说明 不可用时说清原因（人话），可用时可留空 */
  message?: string;
}

export type HealthCheckHandler = (ctx: Ctx, input: HealthCheckIn) => HealthCheckOut | void | Promise<HealthCheckOut | void>;

/** 注册「凭证体检」的实现。 */
export function onHealthCheck(p: Plugin, fn: HealthCheckHandler): void {
  p.register("health_check", async (ctx, raw, out) => {
    const res = await fn(ctx, raw as unknown as HealthCheckIn);
    if (res) out.vars(res);
  });
}

/**
 * 心跳 事件的 payload。
 */
export interface HeartbeatEvent {
  /** 会话 ID */
  chat_id: string;
  /** 时刻 */
  at: string;
}

/** 推一条「心跳」事件。eventId 是幂等键：同一条外部消息重复推只触发一次。 */
export function triggerHeartbeat(ctx: SourceCtx, eventId: string, payload: HeartbeatEvent): Promise<void> {
  return ctx.trigger("heartbeat", eventId, payload);
}

/**
 * 收到消息 事件的 payload。
 */
export interface MessageEvent {
  /** 会话 ID */
  chat_id: string;
  /** 文本 */
  text?: string;
  /** 附件 */
  attachment?: SokelFile;
}

/** 推一条「收到消息」事件。eventId 是幂等键：同一条外部消息重复推只触发一次。 */
export function triggerMessage(ctx: SourceCtx, eventId: string, payload: MessageEvent): Promise<void> {
  return ctx.trigger("message", eventId, payload);
}

/** 按本契约建插件实例。 */
export function newPlugin(cfg: Omit<Config, "contract"> = {}): Plugin {
  return new Plugin({ contract: CONTRACT, ...cfg });
}
