#!/usr/bin/env bash
# Regenerate the skill's generated references from sokel-gen.
#
# Why generate instead of writing them: the format guide, the JSON Schema and the reference
# declaration are compiled into the sokel-gen binary from this repository's own files
# (see embed.go). Re-printing them here keeps one source. A hand-written second copy is the
# drift this exists to prevent — and whoever read the stale one would never know.
#
# Why copy them into the skill at all, rather than telling the reader to run the command: a
# skill has to work for a reader who has not installed the toolchain yet, and for one with no
# network. references/toolchain.md is how they get sokel-gen; everything else has to be
# readable before that.
#
#   scripts/sync-references.sh           regenerate in place
#   scripts/sync-references.sh --check   fail if anything is stale (CI)
#
# Run it from anywhere; paths are resolved against this script.
set -euo pipefail

here=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
refs="$here/../references"
repo=$(cd "$here/../../.." && pwd)     # the SDK repository root
gen=(go run ./cmd/sokel-gen)

check=0
[[ "${1:-}" == "--check" ]] && check=1

banner() {
  printf '<!-- Generated by scripts/sync-references.sh from `sokel-gen %s`. Do not edit; edit the source in the SDK repository and regenerate. -->\n\n' "$1"
}

emit() {            # emit <output file> <banner comment style> <sokel-gen args...>
  local out="$1" style="$2"; shift 2
  local tmp; tmp=$(mktemp)
  case "$style" in
    md)   banner "$*" > "$tmp" ;;
    yaml) printf '# Generated by scripts/sync-references.sh from `sokel-gen %s`. Do not edit.\n' "$*" > "$tmp" ;;
    none) : > "$tmp" ;;                # JSON has no comment syntax; the skill says where it comes from
  esac
  (cd "$repo" && "${gen[@]}" "$@") >> "$tmp"
  if (( check )); then
    if ! diff -q "$tmp" "$out" >/dev/null 2>&1; then
      echo "stale: ${out#"$repo"/}" >&2
      diff -u "$out" "$tmp" | head -40 >&2 || true
      rm -f "$tmp"; exit 1
    fi
    rm -f "$tmp"
  else
    mv "$tmp" "$out"
    echo "wrote ${out#"$repo"/}"
  fi
}

emit "$refs/manifest.md"          md   docs manifest
emit "$refs/manifest.schema.json" none docs schema
emit "$refs/example.manifest.yml" yaml example yaml
emit "$refs/example.python.py"    none example python
emit "$refs/example.node.ts"      none example node

(( check )) && echo "references are current"
exit 0
