// Code generated by sokel-gen. DO NOT EDIT.
//
// The credential contract is generated from the schema declaration.
// Change it there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// Cred is this plugin's credential contract, generated from the schema declaration.
// Read it with sokel.CredentialAs[Cred](ctx), not ctx.Credential()["raw key"]: a misspelled
// raw key compiles fine and silently binds nothing.
type Cred struct {
	APIKey  string `sokel:"api_key" label:"API key" secret:"true"`
	BaseURL string `sokel:"base_url,optional" label:"Service URL" default:"https://api.example.com"`
	Region  string `sokel:"region,optional" label:"Region" default:"cn"`
}

// credentialContract is the credential contract reported to the platform, exactly as declared.
func credentialContract() []contract.Field {
	return []contract.Field{
		{
			Name:     "api_key",
			Label:    "API key",
			Type:     contract.ParamType("secret"),
			Required: true,
		},
		{
			Name:    "base_url",
			Label:   "Service URL",
			Type:    contract.ParamType("text"),
			Default: "https://api.example.com",
		},
		{
			Name:    "region",
			Label:   "Region",
			Type:    contract.ParamType("select"),
			Default: "cn",
			Options: []contract.Option{{Value: "cn", Label: "China"}, {Value: "sg", Label: "Singapore"}},
		},
	}
}

// RegisterCredential reports this plugin's credential contract. It replaces the older
// sokel.WithCredential[Cred]: the fields come from the schema declaration rather than
// reflection, so enum candidates and defaults — things a struct tag cannot express — survive.
func RegisterCredential(h plugin.CredentialHost) { h.SetCredentialContract(credentialContract()) }
