// Code generated by sokel-gen. DO NOT EDIT.
//
// Event payload types and trigger functions are declared in manifest.yml.
// Change an event there, then regenerate.

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// MessageEvent is the payload of the "Message received" event.
// One message picked up by a webhook or a long poll
type MessageEvent struct {
	ChatID     string       `json:"chat_id" sokel:"chat_id"`
	Text       string       `json:"text" sokel:"text"`
	Attachment *plugin.File `json:"attachment" sokel:"attachment"`
}

// HeartbeatEvent is the payload of the "Heartbeat" event.
// A liveness signal from the event source, to prove the "plugin pushes, platform starts a run" path works
type HeartbeatEvent struct {
	ChatID string `json:"chat_id" sokel:"chat_id"`
	At     string `json:"at" sokel:"at"`
}

// DeclareEvents hands this plugin's event contracts to the host.
func DeclareEvents(h plugin.EventHost) {
	events := []contract.Event{
		{ID: "message", Label: "Message received", Desc: "One message picked up by a webhook or a long poll", Fields: []contract.Field{
			{
				Name:     "chat_id",
				Label:    "Chat ID",
				Type:     contract.TString,
				Required: true,
			},
			{
				Name:  "text",
				Label: "Text",
				Type:  contract.TString,
			},
			{
				Name:  "attachment",
				Label: "Attachment",
				Type:  contract.TFile,
			},
		}},
		{ID: "heartbeat", Label: "Heartbeat", Desc: "A liveness signal from the event source, to prove the \"plugin pushes, platform starts a run\" path works", Fields: []contract.Field{
			{
				Name:     "chat_id",
				Label:    "Chat ID",
				Type:     contract.TString,
				Required: true,
			},
			{
				Name:     "at",
				Label:    "Timestamp",
				Type:     contract.TString,
				Required: true,
			},
		}},
	}
	for _, e := range events {
		h.DeclareEvent(e)
	}
	names := []string{"chat_id"}
	fields, _ := contract.ValidateCommonFields(events, names)
	h.DeclareEventsCommon(fields, names)
}

// TriggerMessage pushes one "Message received" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerMessage(ctx plugin.SourceCtx, eventID string, p *MessageEvent) error {
	return ctx.Trigger("message", eventID, p)
}

// TriggerHeartbeat pushes one "Heartbeat" event.
// eventID is the platform's deduplication key: re-pushing the same message triggers once.
func TriggerHeartbeat(ctx plugin.SourceCtx, eventID string, p *HeartbeatEvent) error {
	return ctx.Trigger("heartbeat", eventID, p)
}
