// Code generated by sokel-gen. DO NOT EDIT.
//
// Input/output types are generated from the schema declaration.
// Change a field there, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type Block struct {
	Kind    string `json:"kind" sokel:"kind"`
	Content string `json:"content" sokel:"content"`
}

type DocObject struct {
	Title string `json:"title" sokel:"title"`
	Body  string `json:"body" sokel:"body"`
}

type Point struct {
	X float64 `json:"x" sokel:"x"`
	Y float64 `json:"y" sokel:"y"`
}

type Profile struct {
	Name    string `json:"name" sokel:"name"`
	Age     int    `json:"age" sokel:"age"`
	Address struct {
		City string `json:"city"`
		Zip  string `json:"zip"`
	} `json:"address" sokel:"address"`
}

type ChatStreamIn struct {
	Prompt string `json:"prompt" sokel:"prompt"`
	Chunks int    `json:"chunks" sokel:"chunks"`
}

type ChatStreamOut struct {
	Reply  string `json:"reply" sokel:"reply"`
	Frames int    `json:"frames" sokel:"frames"`
}

type EchoAllIn struct {
	Text    string            `json:"text" sokel:"text"`
	Note    string            `json:"note" sokel:"note"`
	Count   int               `json:"count" sokel:"count"`
	Ratio   float64           `json:"ratio" sokel:"ratio"`
	Flag    bool              `json:"flag" sokel:"flag"`
	Mode    string            `json:"mode" sokel:"mode"`
	Tags    []string          `json:"tags" sokel:"tags"`
	Profile Profile           `json:"profile" sokel:"profile"`
	Points  []Point           `json:"points" sokel:"points"`
	Labels  map[string]string `json:"labels" sokel:"labels"`
	Extra   map[string]any    `json:"extra" sokel:"extra"`
	Doc     EchoAllInDoc      `json:"doc" sokel:"doc"`
}

type EchoAllOut struct {
	Text    string            `json:"text" sokel:"text"`
	Count   int               `json:"count" sokel:"count"`
	Mode    string            `json:"mode" sokel:"mode"`
	Tags    []string          `json:"tags" sokel:"tags"`
	Profile Profile           `json:"profile" sokel:"profile"`
	Points  []Point           `json:"points" sokel:"points"`
	Labels  map[string]string `json:"labels" sokel:"labels"`
	Summary string            `json:"summary" sokel:"summary"`
}

// EchoAllInDoc is the structural union behind EchoAllIn.Doc: one of the shapes below.
type EchoAllInDoc struct{ raw json.RawMessage }

// UnmarshalJSON only keeps the raw bytes; the caller decides which branch to try.
func (u *EchoAllInDoc) UnmarshalJSON(b []byte) error { u.raw = append(u.raw[:0], b...); return nil }

// MarshalJSON hands the bytes back untouched, so a round trip is lossless.
func (u EchoAllInDoc) MarshalJSON() ([]byte, error) {
	if len(u.raw) == 0 {
		return []byte("null"), nil
	}
	return u.raw, nil
}

// Raw returns the raw bytes: the escape hatch when no branch matches.
func (u EchoAllInDoc) Raw() json.RawMessage { return u.raw }

// AsDocObject decodes it as DocObject; a shape mismatch returns false.
func (u EchoAllInDoc) AsDocObject() (*DocObject, bool) {
	var out DocObject
	if len(u.raw) == 0 || json.Unmarshal(u.raw, &out) != nil {
		return nil, false
	}
	return &out, true
}

// AsBlock decodes it as Block; a shape mismatch returns false.
func (u EchoAllInDoc) AsBlock() ([]Block, bool) {
	var out []Block
	if len(u.raw) == 0 || json.Unmarshal(u.raw, &out) != nil {
		return nil, false
	}
	return out, true
}

type FileDigestIn struct {
	File   *plugin.File   `json:"file" sokel:"file"`
	Extras []*plugin.File `json:"extras" sokel:"extras"`
}

type FileDigestOut struct {
	Name       string       `json:"name" sokel:"name"`
	Sha256     string       `json:"sha256" sokel:"sha256"`
	Size       int          `json:"size" sokel:"size"`
	ExtraCount int          `json:"extra_count" sokel:"extra_count"`
	Report     *plugin.File `json:"report" sokel:"report"`
}

type HealthCheckIn struct {
}

type HealthCheckOut struct {
	OK      bool   `json:"ok" sokel:"ok"`
	Message string `json:"message" sokel:"message"`
}

type RowstoreQueryIn struct {
	Table  string `json:"table" sokel:"table"`
	Filter any    `json:"filter" sokel:"filter"`
}

type RowstoreQueryOut struct {
	Rows any `json:"rows" sokel:"rows"`
}

type VectorstoreQueryIn struct {
	KbID      string    `json:"kb_id" sokel:"kb_id"`
	Embedding []float64 `json:"embedding" sokel:"embedding"`
	K         int       `json:"k" sokel:"k"`
}

type VectorstoreQueryOut struct {
	Hits any `json:"hits" sokel:"hits"`
}

type VectorstoreKeywordNgramKeywordQueryIn struct {
	KbID  string `json:"kb_id" sokel:"kb_id"`
	Query string `json:"query" sokel:"query"`
}

type VectorstoreKeywordNgramKeywordQueryOut struct {
	Hits any `json:"hits" sokel:"hits"`
}
