// Code generated by sokel-gen. DO NOT EDIT.
//
// One OnXxx per operation: the signature is fully concrete, so the implementation stays typed.
// Registration goes through plugin.Host, which is **transport-agnostic**: sokel (NATS) and the
// platform's in-process host each implement it, so the same handler runs under either.
// Change an operation in the schema declaration, then regenerate.

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/examples/sysinfo/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnFileDigest registers the implementation of "file_digest".
func OnFileDigest(h plugin.Host, fn func(plugin.Ctx, *FileDigestIn) (*FileDigestOut, error)) {
	h.Register(contract.OperationOf(&schema.FileDigest{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in FileDigestIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSystemInfo registers the implementation of "system_info".
func OnSystemInfo(h plugin.Host, fn func(plugin.Ctx, *SystemInfoIn) (*SystemInfoOut, error)) {
	h.Register(contract.OperationOf(&schema.SystemInfo{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SystemInfoIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
