// Code generated by sokel-gen. DO NOT EDIT.
//
// 每个操作一个 OnXxx：签名完全具体，实现里全程 typed。
// 注册到的是 plugin.Host —— **传输无关**：sokel（NATS）与平台的进程内宿主各实现一份，
// 同一个 handler 因此两边都能挂，差别只有谁来承接。
// 改操作请改 schema 声明，然后重新生成。

package main

import (
	"encoding/json"

	"github.com/sokel-dev/sokel-plugin-sdk/contract"
	"github.com/sokel-dev/sokel-plugin-sdk/examples/sysinfo/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

// OnFileDigest 注册「file_digest」的实现。
func OnFileDigest(h plugin.Host, fn func(plugin.Ctx, *FileDigestIn) (*FileDigestOut, error)) {
	h.Register(contract.OperationOf(&schema.FileDigest{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in FileDigestIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}

// OnSystemInfo 注册「system_info」的实现。
func OnSystemInfo(h plugin.Host, fn func(plugin.Ctx, *SystemInfoIn) (*SystemInfoOut, error)) {
	h.Register(contract.OperationOf(&schema.SystemInfo{}), func(ctx plugin.Ctx, raw json.RawMessage, out plugin.Sink) error {
		var in SystemInfoIn
		if err := contract.BindInput(raw, &in); err != nil {
			return err
		}
		res, err := fn(ctx, &in)
		if err != nil {
			return err
		}
		if res != nil {
			out.Vars(res)
		}
		return nil
	})
}
