// Code generated by sokel-gen. DO NOT EDIT.
//
// 入/出参类型由 schema 声明生成。改字段请改 schema，然后重新生成。

package main

import (
	"github.com/sokel-dev/sokel-plugin-sdk/examples/sysinfo/schema"
	"github.com/sokel-dev/sokel-plugin-sdk/plugin"
)

type FileDigestIn struct {
	File *plugin.File `json:"file" sokel:"file"`
}

type FileDigestOut struct {
	Filename string `json:"filename" sokel:"filename"`
	MD5      string `json:"md5" sokel:"md5"`
	Size     int    `json:"size" sokel:"size"`
}

type SystemInfoIn struct {
	IncludeMemory bool   `json:"include_memory" sokel:"include_memory"`
	Note          string `json:"note" sokel:"note"`
}

type SystemInfoOut struct {
	OK            bool          `json:"ok" sokel:"ok"`
	Hostname      string        `json:"hostname" sokel:"hostname"`
	OS            string        `json:"os" sokel:"os"`
	Arch          string        `json:"arch" sokel:"arch"`
	NumCPU        int           `json:"num_cpu" sokel:"num_cpu"`
	GoVersion     string        `json:"go_version" sokel:"go_version"`
	PID           int           `json:"pid" sokel:"pid"`
	Goroutines    int           `json:"goroutines" sokel:"goroutines"`
	UptimeSeconds int           `json:"uptime_seconds" sokel:"uptime_seconds"`
	StartedAt     string        `json:"started_at" sokel:"started_at"`
	Now           string        `json:"now" sokel:"now"`
	Echo          string        `json:"echo" sokel:"echo"`
	Memory        schema.Memory `json:"memory" sokel:"memory"`
}
